/**
 * Source Classifier — types.
 *
 * Layer 0. Pure domain — no IO, no Prisma, no LLM.
 */

import type { BrandAssetKind } from "@/domain/brand-asset-kinds";

export type PillarKey = "A" | "D" | "V" | "E" | "R" | "T" | "I" | "S";

/**
 * One BrandAsset proposal generated by the classifier from a source.
 * The classifier produces N proposals per source (1 source → N BrandAssets).
 */
export interface SourceClassificationProposal {
  /** Canonical BrandAsset.kind that should be created in the vault. */
  kind: BrandAssetKind;
  /** Human-readable name (auto-generated, operator can edit before promote). */
  name: string;
  /** One-line summary surfaced in the UI proposal card. */
  summary: string;
  /** Confidence 0..1 — heuristic match strength. */
  confidence: number;
  /** Structured payload for INTELLECTUAL assets (sections extracted from the source). */
  content?: Record<string, unknown>;
  /** Source-side citation (chunk range, page, etc.) for traceability. */
  sourceCitation?: {
    charStart?: number;
    charEnd?: number;
    page?: number;
    sectionTitle?: string;
  };
  /** Pillar canonique inferré via KIND_TO_PILLAR. */
  pillarSource: PillarKey;
  /** Heuristic pillar tags hint to warm-start asset-tagger. */
  pillarTagsHint?: Partial<Record<Lowercase<PillarKey>, number>>;
  /** "heuristic" | "vision" | "decomposer" — for telemetry. */
  inferredBy: ClassifierInferenceSource;
}

export type ClassifierInferenceSource = "heuristic" | "vision" | "decomposer";

export interface MimeKindHeuristic {
  /** Canonical BrandAssetKind picked. */
  kind: BrandAssetKind;
  /** Confidence 0..1 the heuristic assigns to its pick. */
  confidence: number;
  /** Whether vision LLM should refine this guess (low confidence + image). */
  needsVision: boolean;
}
