/**
 * commitlint — Conventional Commits enforcement (REFACTOR-CODE-OF-CONDUCT §6).
 */
module.exports = {
  extends: ["@commitlint/config-conventional"],
  rules: {
    "type-enum": [
      2,
      "always",
      [
        "feat",
        "fix",
        "refactor",
        "perf",
        "docs",
        "test",
        "ci",
        "chore",
        "build",
        "revert",
        "governance",
      ],
    ],
    "scope-enum": [
      1,
      "always",
      [
        "domain",
        "mestor",
        "artemis",
        "seshat",
        "thot",
        "oracle",
        "nsp",
        "ui",
        "intake",
        "cockpit",
        "console",
        "agency",
        "creator",
        "neteru",
        "manifests",
        "registry",
        "scorer",
        "ranker",
        "jehuty",
        "tarsis",
        "llm-gateway",
        "audit-trail",
        "governance",
        "ci",
        "deps",
        "meta",
        "seshat-search",
      ],
    ],
    "subject-case": [0],
    "header-max-length": [2, "always", 100],
  },
};
