/**
 * src/server/governance/intent-kinds.ts — Canonical Intent kind catalog.
 *
 * Layer 2. The Phase-3 catalog includes the Mestor v1 kinds plus the 6
 * new ones surfaced by the V5.4 audit (the ranker consumers + the
 * intake → strategy lift + Oracle export).
 *
 * Each Intent kind is associated with:
 *   - the governing Neteru
 *   - the manifest service that handles it
 *   - whether it is async (queued) or sync
 */

import type { Brain } from "./manifest";

export interface IntentKindMeta {
  readonly kind: string;
  readonly governor: Brain;
  readonly handler: string;
  readonly async: boolean;
  readonly description: string;
}

export const INTENT_KINDS: readonly IntentKindMeta[] = [
  // ── Mestor v1 ──
  { kind: "FILL_ADVE", governor: "MESTOR", handler: "mestor", async: false, description: "Fill ADVE pillars from sources." },
  // ADR-0023 — manual operator amend (ADVE only, RTIS forbidden at type level).
  { kind: "OPERATOR_AMEND_PILLAR", governor: "MESTOR", handler: "mestor", async: false, description: "Operator-driven ADVE pillar field amendment (PATCH_DIRECT / LLM_REPHRASE / STRATEGIC_REWRITE)." },
  { kind: "RUN_RTIS_CASCADE", governor: "MESTOR", handler: "mestor", async: false, description: "Run R→T→I→S cascade on a strategy." },
  { kind: "GENERATE_RECOMMENDATIONS", governor: "MESTOR", handler: "notoria", async: false, description: "Generate Notoria recos for a strategy." },
  { kind: "APPLY_RECOMMENDATIONS", governor: "MESTOR", handler: "notoria", async: false, description: "Apply accepted recos." },
  { kind: "BUILD_PLAN", governor: "MESTOR", handler: "mestor", async: false, description: "Build an action plan for a touchpoint/AARRR slice." },
  { kind: "RUN_BOOT_SEQUENCE", governor: "MESTOR", handler: "boot-sequence", async: true, description: "Post-paywall full ADVE+RTIS bootstrap." },
  { kind: "RUN_QUICK_INTAKE", governor: "MESTOR", handler: "quick-intake", async: false, description: "Public rev-9 intake." },

  // ── V5.3 / V5.4 additions (ranker consumers) ──
  { kind: "RANK_PEERS", governor: "SESHAT", handler: "seshat", async: false, description: "Generic peer ranking via context-store ranker." },
  { kind: "SEARCH_BRAND_CONTEXT", governor: "SESHAT", handler: "seshat", async: false, description: "Search across strategies / find peers / search within a strategy." },
  { kind: "INDEX_BRAND_SOURCE", governor: "SESHAT", handler: "seshat", async: true, description: "Index a single BrandDataSource into BRAND_SOURCE chunks for RAG retrieval (operator upload / note / URL)." },
  { kind: "CLASSIFY_BRAND_SOURCE", governor: "MESTOR", handler: "source-classifier", async: true, description: "Heuristic + LLM classification of a BrandDataSource into 1→N BrandAsset kind proposals (no DB writes)." },
  { kind: "PROPOSE_VAULT_FROM_SOURCE", governor: "MESTOR", handler: "source-classifier", async: true, description: "Persist BrandAsset DRAFT proposals derived from a BrandDataSource for operator review in the Cockpit Propositions vault panel." },
  { kind: "JEHUTY_FEED_REFRESH", governor: "SESHAT", handler: "jehuty", async: false, description: "Refresh Jehuty feed (signals + recos + diagnostics)." },
  { kind: "JEHUTY_CURATE", governor: "SESHAT", handler: "jehuty", async: false, description: "Pin / dismiss / trigger curation on Jehuty feed item." },
  { kind: "HYPERVISEUR_PEER_INSIGHTS", governor: "SESHAT", handler: "seshat", async: false, description: "Cross-brand peer insights for the Console hyperviseur." },

  // ── Quick-intake → Strategy automation (Phase 3) ──
  { kind: "LIFT_INTAKE_TO_STRATEGY", governor: "MESTOR", handler: "mestor", async: true, description: "Auto-lift a complete quick-intake into a Strategy + first ADVE→RTIS cascade." },

  // ── Oracle (Phase 7 export, declared now) ──
  { kind: "ENRICH_ORACLE", governor: "ARTEMIS", handler: "strategy-presentation", async: true, description: "Enrich the 21 Oracle sections via Mestor→Artemis→Seshat pipeline." },
  { kind: "EXPORT_ORACLE", governor: "ARTEMIS", handler: "strategy-presentation", async: true, description: "Export Oracle as PDF or Markdown." },

  // ── GLORY ──
  { kind: "INVOKE_GLORY_TOOL", governor: "ARTEMIS", handler: "glory-tools", async: false, description: "Invoke a single atomic GLORY tool." },
  { kind: "EXECUTE_GLORY_SEQUENCE", governor: "ARTEMIS", handler: "artemis", async: true, description: "Run the Artemis sequenceur over a curated chain of GLORY tools." },

  // ── Scoring / pillars ──
  { kind: "SCORE_PILLAR", governor: "INFRASTRUCTURE", handler: "advertis-scorer", async: false, description: "Score a pillar without writing — used by validation flows." },
  { kind: "WRITE_PILLAR", governor: "INFRASTRUCTURE", handler: "pillar-gateway", async: false, description: "Atomic write+score+staleness propagation." },

  // ── Thot (financial brain) ──
  { kind: "CHECK_CAPACITY", governor: "THOT", handler: "financial-brain", async: false, description: "Check operator capacity before LLM call." },
  { kind: "RECORD_COST", governor: "THOT", handler: "financial-brain", async: false, description: "Record realised cost." },
  { kind: "VETO_INTENT", governor: "THOT", handler: "financial-brain", async: false, description: "Veto / downgrade an intent for budget reasons." },

  // ── Audit log corrections ──
  { kind: "CORRECT_INTENT", governor: "MESTOR", handler: "mestor", async: false, description: "Append a correction referencing a previous (immutable) intent. The original row is never mutated." },

  // ── Strangler ──
  { kind: "LEGACY_MUTATION", governor: "INFRASTRUCTURE", handler: "infrastructure", async: false, description: "Synthetic kind logged by the strangler middleware for not-yet-migrated mutations." },

  // ── Tier transitions (palier ZOMBIE → ICONE) — see MISSION.md §5.3 ──
  { kind: "PROMOTE_ZOMBIE_TO_FRAGILE", governor: "MESTOR", handler: "mestor", async: false, description: "Mechanize transition palier ZOMBIE → FRAGILE (substance achieved)." },
  { kind: "PROMOTE_FRAGILE_TO_ORDINAIRE", governor: "MESTOR", handler: "mestor", async: false, description: "Mechanize transition palier FRAGILE → ORDINAIRE (basic propulsion stable)." },
  { kind: "PROMOTE_ORDINAIRE_TO_FORTE", governor: "MESTOR", handler: "mestor", async: false, description: "Mechanize transition palier ORDINAIRE → FORTE (distinction leveraged)." },
  { kind: "PROMOTE_FORTE_TO_CULTE", governor: "MESTOR", handler: "mestor", async: false, description: "Mechanize transition palier FORTE → CULTE (cult formation begins)." },
  { kind: "PROMOTE_CULTE_TO_ICONE", governor: "MESTOR", handler: "mestor", async: false, description: "Mechanize transition palier CULTE → ICONE (cult crystallizes into icon, Overton shift)." },

  // ── Régime apogée — sentinel intents (defend post-ICONE state) — APOGEE §13 ──
  { kind: "MAINTAIN_APOGEE", governor: "MESTOR", handler: "mestor", async: true, description: "Sentinel: maintain ICONE state, refresh evangelist mass, rebuke dilution drift." },
  { kind: "DEFEND_OVERTON", governor: "SESHAT", handler: "seshat", async: true, description: "Sentinel: detect competitor Overton counter-moves, propose Mestor responses." },
  { kind: "EXPAND_TO_ADJACENT_SECTOR", governor: "MESTOR", handler: "mestor", async: true, description: "Sentinel: expand the cult mass to adjacent sectors via cross-sector playbook." },

  // ── Funnel : free showcase → paywalled tiers (Operations + Mission) ──
  { kind: "DEDUCE_ADVE_FROM_OFFER", governor: "MESTOR", handler: "quick-intake", async: false, description: "From a brief offer paragraph, deduce a structured ADVE (4 pillars, scoring, narrative). The free killer-demo." },
  { kind: "EXPORT_RTIS_PDF", governor: "ARTEMIS", handler: "value-report-generator", async: true, description: "Generate paid ADVE+RTIS PDF deliverable (shareable, brand-customized)." },
  { kind: "ACTIVATE_RETAINER", governor: "THOT", handler: "monetization", async: false, description: "Activate a retainer subscription tier (BASE / PRO / ENTERPRISE) for an operator/strategy." },

  // ── Compensating intents (reverse maneuvers) — APOGEE §10.5 ──
  { kind: "ROLLBACK_PILLAR", governor: "MESTOR", handler: "pillar-gateway", async: false, description: "Rollback a previous WRITE_PILLAR — restores the pre-write content + score." },
  { kind: "ROLLBACK_ADVE", governor: "MESTOR", handler: "mestor", async: false, description: "Rollback a FILL_ADVE — restores ADVE to pre-fill state." },
  { kind: "ROLLBACK_RTIS_CASCADE", governor: "MESTOR", handler: "mestor", async: false, description: "Rollback a RUN_RTIS_CASCADE — clears R/T/I/S writes." },
  { kind: "DISCARD_RECOMMENDATIONS", governor: "MESTOR", handler: "notoria", async: false, description: "Discard pending recos generated by GENERATE_RECOMMENDATIONS." },
  { kind: "REVERT_RECOMMENDATIONS", governor: "MESTOR", handler: "notoria", async: false, description: "Revert recos previously applied via APPLY_RECOMMENDATIONS." },
  { kind: "DEMOTE_FRAGILE_TO_ZOMBIE", governor: "MESTOR", handler: "mestor", async: false, description: "Compensator for PROMOTE_ZOMBIE_TO_FRAGILE." },
  { kind: "DEMOTE_ORDINAIRE_TO_FRAGILE", governor: "MESTOR", handler: "mestor", async: false, description: "Compensator for PROMOTE_FRAGILE_TO_ORDINAIRE." },
  { kind: "DEMOTE_FORTE_TO_ORDINAIRE", governor: "MESTOR", handler: "mestor", async: false, description: "Compensator for PROMOTE_ORDINAIRE_TO_FORTE." },
  { kind: "DEMOTE_CULTE_TO_FORTE", governor: "MESTOR", handler: "mestor", async: false, description: "Compensator for PROMOTE_FORTE_TO_CULTE." },
  { kind: "DEMOTE_ICONE_TO_CULTE", governor: "MESTOR", handler: "mestor", async: false, description: "Compensator for PROMOTE_CULTE_TO_ICONE." },

  // ── Plugin extension intents (loyalty-extension demo) ──
  { kind: "COMPUTE_LOYALTY_SCORE", governor: "INFRASTRUCTURE", handler: "loyalty-extension", async: false, description: "Plugin: compute loyalty score from SuperfanProfile + DevotionSnapshot for a strategy." },

  // ── Governance — LLM model policy ──
  { kind: "UPDATE_MODEL_POLICY", governor: "INFRASTRUCTURE", handler: "model-policy", async: false, description: "Update the purpose→model resolution policy used by the LLM Gateway. Hash-chained for full audit trail." },

  // ── Ptah — Forge multimodale (Phase 9, ADR-0009). Cascade Glory→Brief→Forge. ──
  { kind: "PTAH_MATERIALIZE_BRIEF", governor: "MESTOR", handler: "ptah", async: true, description: "Matérialise un ForgeBrief Artemis en asset concret via le provider sélectionné (Magnific/Adobe/Figma/Canva). Async — task créé synchrone, asset livré via webhook reconcile." },
  { kind: "PTAH_RECONCILE_TASK", governor: "MESTOR", handler: "ptah", async: false, description: "Compensating intent — réconcilie un GenerativeTask depuis un webhook provider : download URLs vers CDN, crée AssetVersion, track cost réalisé, emit ASSET_FORGED." },
  { kind: "PTAH_REGENERATE_FADING_ASSET", governor: "MESTOR", handler: "ptah", async: true, description: "Sentinel (régime apogée, Loi 4) : régénère un asset dont l'engagement a chuté >30% vs peak. Cron mensuel pour brands ICONE." },

  // ── Imhotep — Crew Programs full activation (Phase 14, ADR-0019, supersedes ADR-0017). ──
  // 6ème Neter ACTIF. Orchestrateur des satellites matching/talent/team/tier/qc.
  { kind: "IMHOTEP_DRAFT_CREW_PROGRAM", governor: "IMHOTEP", handler: "imhotep", async: false, description: "Draft un programme crew (rôles + budget estimé) pour une stratégie. Phase 14+ retourne status=DRAFT (vrai draft) ; back-compat Phase 13 dormant si strategy absente. Cf. ADR-0010 + ADR-0019." },
  { kind: "IMHOTEP_MATCH_TALENT_TO_MISSION", governor: "IMHOTEP", handler: "imhotep", async: false, description: "Top N candidates pour une mission via matching-engine.suggest, filtrés par minMatchScore. Hint recommendedTalentProfileId = head of list." },
  { kind: "IMHOTEP_ASSEMBLE_CREW", governor: "IMHOTEP", handler: "imhotep", async: false, description: "Assemble une équipe pluri-rôles pour une mission via team-allocator + budget cap. Persiste dans Mission.briefData (anti-doublon — pas de model Crew nouveau)." },
  { kind: "IMHOTEP_EVALUATE_TIER", governor: "IMHOTEP", handler: "imhotep", async: false, description: "Évalue tier d'un creator (PROMOTE/HOLD/DEMOTE) via tier-evaluator + critères met/required. Décision narrative jointe." },
  { kind: "IMHOTEP_ENROLL_FORMATION", governor: "IMHOTEP", handler: "imhotep", async: false, description: "Enroll un user dans un Course Académie. Idempotent — retourne ALREADY_ENROLLED si pré-existant." },
  { kind: "IMHOTEP_CERTIFY_TALENT", governor: "IMHOTEP", handler: "imhotep", async: false, description: "Délivre une TalentCertification (catégorie + métadata + expiry). Appelé après formation complétée ou achievement validé." },
  { kind: "IMHOTEP_QC_DELIVERABLE", governor: "IMHOTEP", handler: "imhotep", async: false, description: "Route un MissionDeliverable vers QC (AUTOMATED via qc-router.automatedQc, ou ASSIGNED via assignReviewer). Si pas de reviewer dispo → ESCALATED." },
  { kind: "IMHOTEP_RECOMMEND_FORMATION", governor: "IMHOTEP", handler: "imhotep", async: false, description: "Propose top 3 Courses pour combler un skill gap (filtre par pillarFocus si fourni). Rationale narratif." },

  // ── Anubis — Comms full activation (Phase 15, ADR-0020, supersedes ADR-0018). ──
  // 7ème Neter ACTIF. Orchestrateur broadcast / ad networks / notification center / credentials vault.
  { kind: "ANUBIS_DRAFT_COMMS_PLAN", governor: "ANUBIS", handler: "anubis", async: false, description: "Draft un plan comms (audience cible, canaux, timing) pour une stratégie/campagne. Phase 15+ status=DRAFT (vrai draft) ; back-compat Phase 13 dormant si strategy absente. Cf. ADR-0011 + ADR-0020." },
  { kind: "ANUBIS_BROADCAST_MESSAGE", governor: "ANUBIS", handler: "anubis", async: true, description: "Lance un broadcast multi-canal pour un CommsPlan. Crée un BroadcastJob queued pour fan-out async. Les providers façades retournent DEFERRED_AWAITING_CREDENTIALS si pas de creds (cf. ADR-0021)." },
  { kind: "ANUBIS_BUY_AD_INVENTORY", governor: "ANUBIS", handler: "anubis", async: true, description: "Achète de l'inventaire ad sur Meta/Google/X/TikTok via le provider sélectionné. Retourne DEFERRED si credentials absentes (Credentials Center à configurer)." },
  { kind: "ANUBIS_SEGMENT_AUDIENCE", governor: "ANUBIS", handler: "anubis", async: false, description: "Segmente une audience selon des règles JSON (sector, devotion tier, geo, etc.). Retourne segment + count estimé." },
  { kind: "ANUBIS_TRACK_DELIVERY", governor: "ANUBIS", handler: "anubis", async: false, description: "Track delivery d'un BroadcastJob (delivered, opened, clicked) via DeliveryReceipt. Pull ou webhook selon provider." },
  { kind: "ANUBIS_REGISTER_CREDENTIAL", governor: "ANUBIS", handler: "anubis", async: false, description: "Enregistre/update un ExternalConnector (API key, OAuth tokens, account ID) pour un provider externe via Credentials Center UI. Cf. ADR-0021." },
  { kind: "ANUBIS_REVOKE_CREDENTIAL", governor: "ANUBIS", handler: "anubis", async: false, description: "Soft-delete un ExternalConnector (status → INACTIVE). Conservé pour traçabilité audit." },
  { kind: "ANUBIS_TEST_CHANNEL", governor: "ANUBIS", handler: "anubis", async: false, description: "Test connectivity d'un canal (envoi d'un ping de validation au provider). Marque ExternalConnector ACTIVE si succès." },
  { kind: "ANUBIS_SCHEDULE_BROADCAST", governor: "ANUBIS", handler: "anubis", async: false, description: "Planifie un broadcast pour un timestamp futur (BroadcastJob.scheduledFor). Lance via cron interne ou scheduler externe." },
  { kind: "ANUBIS_CANCEL_BROADCAST", governor: "ANUBIS", handler: "anubis", async: false, description: "Annule un BroadcastJob queued ou scheduled (status → CANCELLED). No-op si déjà SENT." },
  { kind: "ANUBIS_FETCH_DELIVERY_REPORT", governor: "ANUBIS", handler: "anubis", async: true, description: "Pull metrics du provider externe (delivered, bounced, opened) et update DeliveryReceipt. Retourne DEFERRED si credentials absentes." },

  // ── Anubis — Notification real-time + MCP bidirectionnel (ADR-0023, ADR-0024). ──
  { kind: "ANUBIS_PUSH_NOTIFICATION", governor: "ANUBIS", handler: "anubis", async: false, description: "Push une notification unifiée (in-app via Notification model + NSP SSE realtime + Web Push fan-out + email/SMS optionnels). Respecte NotificationPreference (channels, quiet hours, digestFrequency)." },
  { kind: "ANUBIS_REGISTER_PUSH_SUBSCRIPTION", governor: "ANUBIS", handler: "anubis", async: false, description: "Enregistre un PushSubscription Web Push (endpoint, p256dh, auth) pour un user. Idempotent par endpoint." },
  { kind: "ANUBIS_RENDER_TEMPLATE", governor: "ANUBIS", handler: "anubis", async: false, description: "Rend un NotificationTemplate (Handlebars + MJML) avec vars typées. Retourne { subject?, html?, text }." },
  { kind: "ANUBIS_RUN_DIGEST", governor: "ANUBIS", handler: "anubis", async: true, description: "Cron digest daily/weekly : groupe les notifications IN_APP non-lues par user et envoie un email de récap via template `notification-digest`." },
  { kind: "ANUBIS_MCP_INVOKE_TOOL", governor: "ANUBIS", handler: "anubis", async: false, description: "Invoque un tool MCP entrant (Slack/Notion/Drive/Calendar/Figma/GitHub) via McpRegistry direction=INBOUND. Retourne DEFERRED si credentials absentes (cf. ADR-0021/0022)." },
  { kind: "ANUBIS_MCP_SYNC_REGISTRY", governor: "ANUBIS", handler: "anubis", async: true, description: "Découvre la liste des tools disponibles d'un MCP server inbound et met à jour McpRegistry.toolsCache." },
  { kind: "ANUBIS_MCP_REGISTER_SERVER", governor: "ANUBIS", handler: "anubis", async: false, description: "Enregistre un McpRegistry (INBOUND ou OUTBOUND) avec credentialRef vers ExternalConnector. Cf. ADR-0023." },

  // ── BrandAsset / Brand Vault (Phase 10, ADR-0012). Cycle de vie gouverné. ──
  { kind: "SELECT_BRAND_ASSET", governor: "MESTOR", handler: "brand-vault", async: false, description: "Sélectionne un BrandAsset parmi un batch de candidats CANDIDATE → SELECTED (et REJECTED pour les autres). Optionnellement promote en ACTIVE et update Campaign.active{Kind}Id." },
  { kind: "PROMOTE_BRAND_ASSET_TO_ACTIVE", governor: "MESTOR", handler: "brand-vault", async: false, description: "Promote un BrandAsset SELECTED en ACTIVE et update Campaign.active{Kind}Id (BigIdea/Brief/Claim/Manifesto/KvBrief)." },
  { kind: "SUPERSEDE_BRAND_ASSET", governor: "MESTOR", handler: "brand-vault", async: false, description: "Remplace un BrandAsset ACTIVE par une nouvelle version. L'ancien passe SUPERSEDED, le nouveau ACTIVE. Lineage parent/version préservée." },
  { kind: "ARCHIVE_BRAND_ASSET", governor: "MESTOR", handler: "brand-vault", async: false, description: "Archive un BrandAsset (mort rituelle — lecture seule). Lineage préservée." },

  // ── Error Vault (Phase 11) — observabilité runtime. ──
  { kind: "CAPTURE_ERROR_EVENT", governor: "INFRASTRUCTURE", handler: "error-vault", async: false, description: "Capture une erreur runtime (server/client/Prisma/NSP/Ptah/cron/webhook/stress-test) avec dedup par signature." },
  { kind: "RESOLVE_ERROR_EVENT", governor: "INFRASTRUCTURE", handler: "error-vault", async: false, description: "Marque un ErrorEvent comme résolu (ou false-positive connu — auto-resolve futurs occurrences)." },

// ── AUTOGEN: legacy-intent-kinds — DO NOT EDIT MANUALLY ──
  // 293 legacy mutation kinds auto-generated from strangler routers.
  // Source : scripts/generate-legacy-intent-kinds.ts. Re-run after any router mutation rename.
  { kind: "LEGACY_ADVERTIS_SCORER_BATCH_SCORE", governor: "INFRASTRUCTURE", handler: "advertis-scorer", async: false, description: "Strangler-promoted mutation 'batchScore' from router 'advertis-scorer'." },
  { kind: "LEGACY_ADVERTIS_SCORER_RECALCULATE", governor: "INFRASTRUCTURE", handler: "advertis-scorer", async: false, description: "Strangler-promoted mutation 'recalculate' from router 'advertis-scorer'." },
  { kind: "LEGACY_ADVERTIS_SCORER_SCORE_OBJECT", governor: "INFRASTRUCTURE", handler: "advertis-scorer", async: false, description: "Strangler-promoted mutation 'scoreObject' from router 'advertis-scorer'." },
  { kind: "LEGACY_ADVERTIS_SCORER_SNAPSHOT_ALL", governor: "INFRASTRUCTURE", handler: "advertis-scorer", async: false, description: "Strangler-promoted mutation 'snapshotAll' from router 'advertis-scorer'." },
  { kind: "LEGACY_ANALYTICS_GENERATE_INSIGHT", governor: "INFRASTRUCTURE", handler: "analytics", async: false, description: "Strangler-promoted mutation 'generateInsight' from router 'analytics'." },
  { kind: "LEGACY_ANALYTICS_RECORD_COHORT", governor: "INFRASTRUCTURE", handler: "analytics", async: false, description: "Strangler-promoted mutation 'recordCohort' from router 'analytics'." },
  { kind: "LEGACY_ANALYTICS_RECORD_COMPETITOR", governor: "INFRASTRUCTURE", handler: "analytics", async: false, description: "Strangler-promoted mutation 'recordCompetitor' from router 'analytics'." },
  { kind: "LEGACY_ANALYTICS_RECORD_EVENT", governor: "INFRASTRUCTURE", handler: "analytics", async: false, description: "Strangler-promoted mutation 'recordEvent' from router 'analytics'." },
  { kind: "LEGACY_ATTRIBUTION_ROUTER_CREATE", governor: "INFRASTRUCTURE", handler: "attribution-router", async: false, description: "Strangler-promoted mutation 'create' from router 'attribution-router'." },
  { kind: "LEGACY_BOOT_SEQUENCE_ADVANCE", governor: "INFRASTRUCTURE", handler: "boot-sequence", async: false, description: "Strangler-promoted mutation 'advance' from router 'boot-sequence'." },
  { kind: "LEGACY_BOOT_SEQUENCE_CHAT", governor: "INFRASTRUCTURE", handler: "boot-sequence", async: false, description: "Strangler-promoted mutation 'chat' from router 'boot-sequence'." },
  { kind: "LEGACY_BOOT_SEQUENCE_COMPLETE", governor: "INFRASTRUCTURE", handler: "boot-sequence", async: false, description: "Strangler-promoted mutation 'complete' from router 'boot-sequence'." },
  { kind: "LEGACY_BOOT_SEQUENCE_CONVERT_TO_STRATEGY", governor: "INFRASTRUCTURE", handler: "boot-sequence", async: false, description: "Strangler-promoted mutation 'convertToStrategy' from router 'boot-sequence'." },
  { kind: "LEGACY_BOOT_SEQUENCE_START", governor: "INFRASTRUCTURE", handler: "boot-sequence", async: false, description: "Strangler-promoted mutation 'start' from router 'boot-sequence'." },
  { kind: "LEGACY_BOUTIQUE_CREATE_ITEM", governor: "INFRASTRUCTURE", handler: "boutique", async: false, description: "Strangler-promoted mutation 'createItem' from router 'boutique'." },
  { kind: "LEGACY_BOUTIQUE_ORDER", governor: "INFRASTRUCTURE", handler: "boutique", async: false, description: "Strangler-promoted mutation 'order' from router 'boutique'." },
  { kind: "LEGACY_BOUTIQUE_UPDATE_ITEM", governor: "INFRASTRUCTURE", handler: "boutique", async: false, description: "Strangler-promoted mutation 'updateItem' from router 'boutique'." },
  { kind: "LEGACY_BOUTIQUE_UPDATE_ORDER_STATUS", governor: "INFRASTRUCTURE", handler: "boutique", async: false, description: "Strangler-promoted mutation 'updateOrderStatus' from router 'boutique'." },
  { kind: "LEGACY_BRAND_VAULT_CREATE", governor: "INFRASTRUCTURE", handler: "brand-vault", async: false, description: "Strangler-promoted mutation 'create' from router 'brand-vault'." },
  { kind: "LEGACY_BRAND_VAULT_DELETE", governor: "INFRASTRUCTURE", handler: "brand-vault", async: false, description: "Strangler-promoted mutation 'delete' from router 'brand-vault'." },
  { kind: "LEGACY_BRAND_VAULT_PURGE", governor: "INFRASTRUCTURE", handler: "brand-vault", async: false, description: "Strangler-promoted mutation 'purge' from router 'brand-vault'." },
  { kind: "LEGACY_BRAND_VAULT_UPDATE_TAGS", governor: "INFRASTRUCTURE", handler: "brand-vault", async: false, description: "Strangler-promoted mutation 'updateTags' from router 'brand-vault'." },
  { kind: "LEGACY_BRIEF_INGEST_ADVANCE", governor: "INFRASTRUCTURE", handler: "brief-ingest", async: false, description: "Strangler-promoted mutation 'advance' from router 'brief-ingest'." },
  { kind: "LEGACY_BRIEF_INGEST_CONFIRM", governor: "INFRASTRUCTURE", handler: "brief-ingest", async: false, description: "Strangler-promoted mutation 'confirm' from router 'brief-ingest'." },
  { kind: "LEGACY_BRIEF_INGEST_PREVIEW", governor: "INFRASTRUCTURE", handler: "brief-ingest", async: false, description: "Strangler-promoted mutation 'preview' from router 'brief-ingest'." },
  { kind: "LEGACY_CAMPAIGN_CREATE", governor: "INFRASTRUCTURE", handler: "campaign", async: false, description: "Strangler-promoted mutation 'create' from router 'campaign'." },
  { kind: "LEGACY_CAMPAIGN_DELETE", governor: "INFRASTRUCTURE", handler: "campaign", async: false, description: "Strangler-promoted mutation 'delete' from router 'campaign'." },
  { kind: "LEGACY_CAMPAIGN_MANAGER_ADD_DEPENDENCY", governor: "INFRASTRUCTURE", handler: "campaign-manager", async: false, description: "Strangler-promoted mutation 'addDependency' from router 'campaign-manager'." },
  { kind: "LEGACY_CAMPAIGN_MANAGER_ADD_TEAM_MEMBER", governor: "INFRASTRUCTURE", handler: "campaign-manager", async: false, description: "Strangler-promoted mutation 'addTeamMember' from router 'campaign-manager'." },
  { kind: "LEGACY_CAMPAIGN_MANAGER_COMPLETE_MILESTONE", governor: "INFRASTRUCTURE", handler: "campaign-manager", async: false, description: "Strangler-promoted mutation 'completeMilestone' from router 'campaign-manager'." },
  { kind: "LEGACY_CAMPAIGN_MANAGER_CREATE_BRIEF", governor: "INFRASTRUCTURE", handler: "campaign-manager", async: false, description: "Strangler-promoted mutation 'createBrief' from router 'campaign-manager'." },
  { kind: "LEGACY_CAMPAIGN_MANAGER_CREATE_BUDGET_LINE", governor: "INFRASTRUCTURE", handler: "campaign-manager", async: false, description: "Strangler-promoted mutation 'createBudgetLine' from router 'campaign-manager'." },
  { kind: "LEGACY_CAMPAIGN_MANAGER_CREATE_EXECUTION", governor: "INFRASTRUCTURE", handler: "campaign-manager", async: false, description: "Strangler-promoted mutation 'createExecution' from router 'campaign-manager'." },
  { kind: "LEGACY_CAMPAIGN_MANAGER_CREATE_FROM_TEMPLATE", governor: "INFRASTRUCTURE", handler: "campaign-manager", async: false, description: "Strangler-promoted mutation 'createFromTemplate' from router 'campaign-manager'." },
  { kind: "LEGACY_CAMPAIGN_MANAGER_CREATE_MILESTONE", governor: "INFRASTRUCTURE", handler: "campaign-manager", async: false, description: "Strangler-promoted mutation 'createMilestone' from router 'campaign-manager'." },
  { kind: "LEGACY_CAMPAIGN_MANAGER_DECIDE_APPROVAL", governor: "INFRASTRUCTURE", handler: "campaign-manager", async: false, description: "Strangler-promoted mutation 'decideApproval' from router 'campaign-manager'." },
  { kind: "LEGACY_CAMPAIGN_MANAGER_DELETE", governor: "INFRASTRUCTURE", handler: "campaign-manager", async: false, description: "Strangler-promoted mutation 'delete' from router 'campaign-manager'." },
  { kind: "LEGACY_CAMPAIGN_MANAGER_DELETE_AMPLIFICATION", governor: "INFRASTRUCTURE", handler: "campaign-manager", async: false, description: "Strangler-promoted mutation 'deleteAmplification' from router 'campaign-manager'." },
  { kind: "LEGACY_CAMPAIGN_MANAGER_DELETE_BUDGET_LINE", governor: "INFRASTRUCTURE", handler: "campaign-manager", async: false, description: "Strangler-promoted mutation 'deleteBudgetLine' from router 'campaign-manager'." },
  { kind: "LEGACY_CAMPAIGN_MANAGER_DELETE_FIELD_OP", governor: "INFRASTRUCTURE", handler: "campaign-manager", async: false, description: "Strangler-promoted mutation 'deleteFieldOp' from router 'campaign-manager'." },
  { kind: "LEGACY_CAMPAIGN_MANAGER_DELETE_MILESTONE", governor: "INFRASTRUCTURE", handler: "campaign-manager", async: false, description: "Strangler-promoted mutation 'deleteMilestone' from router 'campaign-manager'." },
  { kind: "LEGACY_CAMPAIGN_MANAGER_GENERATE_CREATIVE_BRIEF", governor: "INFRASTRUCTURE", handler: "campaign-manager", async: false, description: "Strangler-promoted mutation 'generateCreativeBrief' from router 'campaign-manager'." },
  { kind: "LEGACY_CAMPAIGN_MANAGER_GENERATE_MEDIA_BRIEF", governor: "INFRASTRUCTURE", handler: "campaign-manager", async: false, description: "Strangler-promoted mutation 'generateMediaBrief' from router 'campaign-manager'." },
  { kind: "LEGACY_CAMPAIGN_MANAGER_GENERATE_PRODUCTION_BRIEF", governor: "INFRASTRUCTURE", handler: "campaign-manager", async: false, description: "Strangler-promoted mutation 'generateProductionBrief' from router 'campaign-manager'." },
  { kind: "LEGACY_CAMPAIGN_MANAGER_GENERATE_REPORT", governor: "INFRASTRUCTURE", handler: "campaign-manager", async: false, description: "Strangler-promoted mutation 'generateReport' from router 'campaign-manager'." },
  { kind: "LEGACY_CAMPAIGN_MANAGER_GENERATE_VENDOR_BRIEF", governor: "INFRASTRUCTURE", handler: "campaign-manager", async: false, description: "Strangler-promoted mutation 'generateVendorBrief' from router 'campaign-manager'." },
  { kind: "LEGACY_CAMPAIGN_MANAGER_LINK_MISSION", governor: "INFRASTRUCTURE", handler: "campaign-manager", async: false, description: "Strangler-promoted mutation 'linkMission' from router 'campaign-manager'." },
  { kind: "LEGACY_CAMPAIGN_MANAGER_LINK_PUBLICATION", governor: "INFRASTRUCTURE", handler: "campaign-manager", async: false, description: "Strangler-promoted mutation 'linkPublication' from router 'campaign-manager'." },
  { kind: "LEGACY_CAMPAIGN_MANAGER_LINK_SIGNAL", governor: "INFRASTRUCTURE", handler: "campaign-manager", async: false, description: "Strangler-promoted mutation 'linkSignal' from router 'campaign-manager'." },
  { kind: "LEGACY_CAMPAIGN_MANAGER_MIGRATE", governor: "INFRASTRUCTURE", handler: "campaign-manager", async: false, description: "Strangler-promoted mutation 'migrate' from router 'campaign-manager'." },
  { kind: "LEGACY_CAMPAIGN_MANAGER_PUBLISH_ASSET_TO_BRAND_VAULT", governor: "INFRASTRUCTURE", handler: "campaign-manager", async: false, description: "Strangler-promoted mutation 'publishAssetToBrandVault' from router 'campaign-manager'." },
  { kind: "LEGACY_CAMPAIGN_MANAGER_RECORD_A_A_R_R_METRIC", governor: "INFRASTRUCTURE", handler: "campaign-manager", async: false, description: "Strangler-promoted mutation 'recordAARRMetric' from router 'campaign-manager'." },
  { kind: "LEGACY_CAMPAIGN_MANAGER_REJECT_FIELD_REPORT", governor: "INFRASTRUCTURE", handler: "campaign-manager", async: false, description: "Strangler-promoted mutation 'rejectFieldReport' from router 'campaign-manager'." },
  { kind: "LEGACY_CAMPAIGN_MANAGER_REMOVE_TEAM_MEMBER", governor: "INFRASTRUCTURE", handler: "campaign-manager", async: false, description: "Strangler-promoted mutation 'removeTeamMember' from router 'campaign-manager'." },
  { kind: "LEGACY_CAMPAIGN_MANAGER_REQUEST_APPROVAL", governor: "INFRASTRUCTURE", handler: "campaign-manager", async: false, description: "Strangler-promoted mutation 'requestApproval' from router 'campaign-manager'." },
  { kind: "LEGACY_CAMPAIGN_MANAGER_SAVE_AS_TEMPLATE", governor: "INFRASTRUCTURE", handler: "campaign-manager", async: false, description: "Strangler-promoted mutation 'saveAsTemplate' from router 'campaign-manager'." },
  { kind: "LEGACY_CAMPAIGN_MANAGER_SET_DEVOTION_OBJECTIVE", governor: "INFRASTRUCTURE", handler: "campaign-manager", async: false, description: "Strangler-promoted mutation 'setDevotionObjective' from router 'campaign-manager'." },
  { kind: "LEGACY_CAMPAIGN_MANAGER_TRANSITION", governor: "INFRASTRUCTURE", handler: "campaign-manager", async: false, description: "Strangler-promoted mutation 'transition' from router 'campaign-manager'." },
  { kind: "LEGACY_CAMPAIGN_MANAGER_TRANSITION_EXECUTION", governor: "INFRASTRUCTURE", handler: "campaign-manager", async: false, description: "Strangler-promoted mutation 'transitionExecution' from router 'campaign-manager'." },
  { kind: "LEGACY_CAMPAIGN_MANAGER_UNLINK_ENTITY", governor: "INFRASTRUCTURE", handler: "campaign-manager", async: false, description: "Strangler-promoted mutation 'unlinkEntity' from router 'campaign-manager'." },
  { kind: "LEGACY_CAMPAIGN_MANAGER_UPDATE", governor: "INFRASTRUCTURE", handler: "campaign-manager", async: false, description: "Strangler-promoted mutation 'update' from router 'campaign-manager'." },
  { kind: "LEGACY_CAMPAIGN_MANAGER_UPDATE_ACTION", governor: "INFRASTRUCTURE", handler: "campaign-manager", async: false, description: "Strangler-promoted mutation 'updateAction' from router 'campaign-manager'." },
  { kind: "LEGACY_CAMPAIGN_MANAGER_UPDATE_BRIEF", governor: "INFRASTRUCTURE", handler: "campaign-manager", async: false, description: "Strangler-promoted mutation 'updateBrief' from router 'campaign-manager'." },
  { kind: "LEGACY_CAMPAIGN_MANAGER_UPDATE_BUDGET_LINE", governor: "INFRASTRUCTURE", handler: "campaign-manager", async: false, description: "Strangler-promoted mutation 'updateBudgetLine' from router 'campaign-manager'." },
  { kind: "LEGACY_CAMPAIGN_MANAGER_UPDATE_EXECUTION", governor: "INFRASTRUCTURE", handler: "campaign-manager", async: false, description: "Strangler-promoted mutation 'updateExecution' from router 'campaign-manager'." },
  { kind: "LEGACY_CAMPAIGN_MANAGER_UPDATE_FIELD_OP", governor: "INFRASTRUCTURE", handler: "campaign-manager", async: false, description: "Strangler-promoted mutation 'updateFieldOp' from router 'campaign-manager'." },
  { kind: "LEGACY_CAMPAIGN_MANAGER_UPDATE_MILESTONE", governor: "INFRASTRUCTURE", handler: "campaign-manager", async: false, description: "Strangler-promoted mutation 'updateMilestone' from router 'campaign-manager'." },
  { kind: "LEGACY_CAMPAIGN_MANAGER_UPDATE_TEAM_MEMBER", governor: "INFRASTRUCTURE", handler: "campaign-manager", async: false, description: "Strangler-promoted mutation 'updateTeamMember' from router 'campaign-manager'." },
  { kind: "LEGACY_CAMPAIGN_MANAGER_UPLOAD_ASSET", governor: "INFRASTRUCTURE", handler: "campaign-manager", async: false, description: "Strangler-promoted mutation 'uploadAsset' from router 'campaign-manager'." },
  { kind: "LEGACY_CAMPAIGN_MANAGER_VALIDATE_FIELD_REPORT", governor: "INFRASTRUCTURE", handler: "campaign-manager", async: false, description: "Strangler-promoted mutation 'validateFieldReport' from router 'campaign-manager'." },
  { kind: "LEGACY_CAMPAIGN_MANAGER_VERSION_ASSET", governor: "INFRASTRUCTURE", handler: "campaign-manager", async: false, description: "Strangler-promoted mutation 'versionAsset' from router 'campaign-manager'." },
  { kind: "LEGACY_CAMPAIGN_UPDATE", governor: "INFRASTRUCTURE", handler: "campaign", async: false, description: "Strangler-promoted mutation 'update' from router 'campaign'." },
  { kind: "LEGACY_CLIENT_ADD_BRAND", governor: "INFRASTRUCTURE", handler: "client", async: false, description: "Strangler-promoted mutation 'addBrand' from router 'client'." },
  { kind: "LEGACY_CLIENT_CREATE", governor: "INFRASTRUCTURE", handler: "client", async: false, description: "Strangler-promoted mutation 'create' from router 'client'." },
  { kind: "LEGACY_CLIENT_DELETE", governor: "INFRASTRUCTURE", handler: "client", async: false, description: "Strangler-promoted mutation 'delete' from router 'client'." },
  { kind: "LEGACY_CLUB_JOIN", governor: "INFRASTRUCTURE", handler: "club", async: false, description: "Strangler-promoted mutation 'join' from router 'club'." },
  { kind: "LEGACY_CLUB_LEAVE", governor: "INFRASTRUCTURE", handler: "club", async: false, description: "Strangler-promoted mutation 'leave' from router 'club'." },
  { kind: "LEGACY_COMMISSION_CALCULATE", governor: "INFRASTRUCTURE", handler: "commission", async: false, description: "Strangler-promoted mutation 'calculate' from router 'commission'." },
  { kind: "LEGACY_COMMISSION_CALCULATE_ON_COMPLETE", governor: "INFRASTRUCTURE", handler: "commission", async: false, description: "Strangler-promoted mutation 'calculateOnComplete' from router 'commission'." },
  { kind: "LEGACY_COMMISSION_GENERATE_PAYMENT_ORDER", governor: "INFRASTRUCTURE", handler: "commission", async: false, description: "Strangler-promoted mutation 'generatePaymentOrder' from router 'commission'." },
  { kind: "LEGACY_COMMISSION_MARK_PAID", governor: "INFRASTRUCTURE", handler: "commission", async: false, description: "Strangler-promoted mutation 'markPaid' from router 'commission'." },
  { kind: "LEGACY_CONNECTORS_DISCONNECT", governor: "INFRASTRUCTURE", handler: "connectors", async: false, description: "Strangler-promoted mutation 'disconnect' from router 'connectors'." },
  { kind: "LEGACY_CONNECTORS_SYNC", governor: "INFRASTRUCTURE", handler: "connectors", async: false, description: "Strangler-promoted mutation 'sync' from router 'connectors'." },
  { kind: "LEGACY_CONNECTORS_UPSERT", governor: "INFRASTRUCTURE", handler: "connectors", async: false, description: "Strangler-promoted mutation 'upsert' from router 'connectors'." },
  { kind: "LEGACY_CONTRACT_CREATE", governor: "INFRASTRUCTURE", handler: "contract", async: false, description: "Strangler-promoted mutation 'create' from router 'contract'." },
  { kind: "LEGACY_CONTRACT_CREATE_ESCROW", governor: "INFRASTRUCTURE", handler: "contract", async: false, description: "Strangler-promoted mutation 'createEscrow' from router 'contract'." },
  { kind: "LEGACY_CONTRACT_MEET_ESCROW_CONDITION", governor: "INFRASTRUCTURE", handler: "contract", async: false, description: "Strangler-promoted mutation 'meetEscrowCondition' from router 'contract'." },
  { kind: "LEGACY_CONTRACT_RELEASE_ESCROW", governor: "INFRASTRUCTURE", handler: "contract", async: false, description: "Strangler-promoted mutation 'releaseEscrow' from router 'contract'." },
  { kind: "LEGACY_CONTRACT_SIGN", governor: "INFRASTRUCTURE", handler: "contract", async: false, description: "Strangler-promoted mutation 'sign' from router 'contract'." },
  { kind: "LEGACY_CONTRACT_UPDATE_STATUS", governor: "INFRASTRUCTURE", handler: "contract", async: false, description: "Strangler-promoted mutation 'updateStatus' from router 'contract'." },
  { kind: "LEGACY_CRM_ADD_ACTIVITY", governor: "INFRASTRUCTURE", handler: "crm", async: false, description: "Strangler-promoted mutation 'addActivity' from router 'crm'." },
  { kind: "LEGACY_CRM_ADD_NOTE", governor: "INFRASTRUCTURE", handler: "crm", async: false, description: "Strangler-promoted mutation 'addNote' from router 'crm'." },
  { kind: "LEGACY_CRM_ADVANCE_DEAL", governor: "INFRASTRUCTURE", handler: "crm", async: false, description: "Strangler-promoted mutation 'advanceDeal' from router 'crm'." },
  { kind: "LEGACY_CRM_CONVERT_TO_STRATEGY", governor: "INFRASTRUCTURE", handler: "crm", async: false, description: "Strangler-promoted mutation 'convertToStrategy' from router 'crm'." },
  { kind: "LEGACY_CRM_CREATE_DEAL", governor: "INFRASTRUCTURE", handler: "crm", async: false, description: "Strangler-promoted mutation 'createDeal' from router 'crm'." },
  { kind: "LEGACY_CRM_CREATE_DEAL_FROM_INTAKE", governor: "INFRASTRUCTURE", handler: "crm", async: false, description: "Strangler-promoted mutation 'createDealFromIntake' from router 'crm'." },
  { kind: "LEGACY_CRM_LOSE_DEAL", governor: "INFRASTRUCTURE", handler: "crm", async: false, description: "Strangler-promoted mutation 'loseDeal' from router 'crm'." },
  { kind: "LEGACY_CRM_MOVE_DEAL_TO_STAGE", governor: "INFRASTRUCTURE", handler: "crm", async: false, description: "Strangler-promoted mutation 'moveDealToStage' from router 'crm'." },
  { kind: "LEGACY_CRM_UPDATE_DEAL", governor: "INFRASTRUCTURE", handler: "crm", async: false, description: "Strangler-promoted mutation 'updateDeal' from router 'crm'." },
  { kind: "LEGACY_CULT_INDEX_CALCULATE", governor: "INFRASTRUCTURE", handler: "cult-index", async: false, description: "Strangler-promoted mutation 'calculate' from router 'cult-index'." },
  { kind: "LEGACY_DELIVERABLE_TRACKING_ADD_SIGNAL", governor: "INFRASTRUCTURE", handler: "deliverable-tracking", async: false, description: "Strangler-promoted mutation 'addSignal' from router 'deliverable-tracking'." },
  { kind: "LEGACY_DELIVERABLE_TRACKING_CREATE", governor: "INFRASTRUCTURE", handler: "deliverable-tracking", async: false, description: "Strangler-promoted mutation 'create' from router 'deliverable-tracking'." },
  { kind: "LEGACY_DELIVERABLE_TRACKING_EXPIRE", governor: "INFRASTRUCTURE", handler: "deliverable-tracking", async: false, description: "Strangler-promoted mutation 'expire' from router 'deliverable-tracking'." },
  { kind: "LEGACY_DEVOTION_LADDER_RECONCILE_AMBASSADORS", governor: "INFRASTRUCTURE", handler: "devotion-ladder", async: false, description: "Strangler-promoted mutation 'reconcileAmbassadors' from router 'devotion-ladder'." },
  { kind: "LEGACY_DEVOTION_LADDER_SET_OBJECTIVE", governor: "INFRASTRUCTURE", handler: "devotion-ladder", async: false, description: "Strangler-promoted mutation 'setObjective' from router 'devotion-ladder'." },
  { kind: "LEGACY_DEVOTION_LADDER_SNAPSHOT", governor: "INFRASTRUCTURE", handler: "devotion-ladder", async: false, description: "Strangler-promoted mutation 'snapshot' from router 'devotion-ladder'." },
  { kind: "LEGACY_DEVOTION_LADDER_SYNC_TO_CULT_INDEX", governor: "INFRASTRUCTURE", handler: "devotion-ladder", async: false, description: "Strangler-promoted mutation 'syncToCultIndex' from router 'devotion-ladder'." },
  { kind: "LEGACY_DRIVER_ACTIVATE", governor: "INFRASTRUCTURE", handler: "driver", async: false, description: "Strangler-promoted mutation 'activate' from router 'driver'." },
  { kind: "LEGACY_DRIVER_CLONE_FOR_MARKET", governor: "INFRASTRUCTURE", handler: "driver", async: false, description: "Strangler-promoted mutation 'cloneForMarket' from router 'driver'." },
  { kind: "LEGACY_DRIVER_DEACTIVATE", governor: "INFRASTRUCTURE", handler: "driver", async: false, description: "Strangler-promoted mutation 'deactivate' from router 'driver'." },
  { kind: "LEGACY_DRIVER_DELETE", governor: "INFRASTRUCTURE", handler: "driver", async: false, description: "Strangler-promoted mutation 'delete' from router 'driver'." },
  { kind: "LEGACY_DRIVER_GENERATE_SPECS", governor: "INFRASTRUCTURE", handler: "driver", async: false, description: "Strangler-promoted mutation 'generateSpecs' from router 'driver'." },
  { kind: "LEGACY_DRIVER_LINK_GLORY_TOOL", governor: "INFRASTRUCTURE", handler: "driver", async: false, description: "Strangler-promoted mutation 'linkGloryTool' from router 'driver'." },
  { kind: "LEGACY_DRIVER_SET_PRIMARY", governor: "INFRASTRUCTURE", handler: "driver", async: false, description: "Strangler-promoted mutation 'setPrimary' from router 'driver'." },
  { kind: "LEGACY_DRIVER_TRANSLATE_BRIEF", governor: "INFRASTRUCTURE", handler: "driver", async: false, description: "Strangler-promoted mutation 'translateBrief' from router 'driver'." },
  { kind: "LEGACY_DRIVER_UNLINK_GLORY_TOOL", governor: "INFRASTRUCTURE", handler: "driver", async: false, description: "Strangler-promoted mutation 'unlinkGloryTool' from router 'driver'." },
  { kind: "LEGACY_DRIVER_UPDATE", governor: "INFRASTRUCTURE", handler: "driver", async: false, description: "Strangler-promoted mutation 'update' from router 'driver'." },
  { kind: "LEGACY_EDITORIAL_ADD_COMMENT", governor: "INFRASTRUCTURE", handler: "editorial", async: false, description: "Strangler-promoted mutation 'addComment' from router 'editorial'." },
  { kind: "LEGACY_EDITORIAL_CREATE", governor: "INFRASTRUCTURE", handler: "editorial", async: false, description: "Strangler-promoted mutation 'create' from router 'editorial'." },
  { kind: "LEGACY_EDITORIAL_PUBLISH", governor: "INFRASTRUCTURE", handler: "editorial", async: false, description: "Strangler-promoted mutation 'publish' from router 'editorial'." },
  { kind: "LEGACY_EVENT_MARK_ATTENDED", governor: "INFRASTRUCTURE", handler: "event", async: false, description: "Strangler-promoted mutation 'markAttended' from router 'event'." },
  { kind: "LEGACY_EVENT_REGISTER", governor: "INFRASTRUCTURE", handler: "event", async: false, description: "Strangler-promoted mutation 'register' from router 'event'." },
  { kind: "LEGACY_EVENT_UNREGISTER", governor: "INFRASTRUCTURE", handler: "event", async: false, description: "Strangler-promoted mutation 'unregister' from router 'event'." },
  { kind: "LEGACY_FRAMEWORK_EXECUTE", governor: "INFRASTRUCTURE", handler: "framework", async: false, description: "Strangler-promoted mutation 'execute' from router 'framework'." },
  { kind: "LEGACY_FRAMEWORK_RUN_BATCH", governor: "INFRASTRUCTURE", handler: "framework", async: false, description: "Strangler-promoted mutation 'runBatch' from router 'framework'." },
  { kind: "LEGACY_FRAMEWORK_RUN_PILLAR_DIAGNOSTIC", governor: "INFRASTRUCTURE", handler: "framework", async: false, description: "Strangler-promoted mutation 'runPillarDiagnostic' from router 'framework'." },
  { kind: "LEGACY_FRAMEWORK_SCHEDULE_EXECUTION", governor: "INFRASTRUCTURE", handler: "framework", async: false, description: "Strangler-promoted mutation 'scheduleExecution' from router 'framework'." },
  { kind: "LEGACY_GLORY_AUTO_COMPLETE", governor: "INFRASTRUCTURE", handler: "glory", async: false, description: "Strangler-promoted mutation 'autoComplete' from router 'glory'." },
  { kind: "LEGACY_GLORY_EXECUTE", governor: "INFRASTRUCTURE", handler: "glory", async: false, description: "Strangler-promoted mutation 'execute' from router 'glory'." },
  { kind: "LEGACY_GLORY_EXECUTE_BRAND_PIPELINE", governor: "INFRASTRUCTURE", handler: "glory", async: false, description: "Strangler-promoted mutation 'executeBrandPipeline' from router 'glory'." },
  { kind: "LEGACY_GLORY_EXECUTE_SEQUENCE", governor: "INFRASTRUCTURE", handler: "glory", async: false, description: "Strangler-promoted mutation 'executeSequence' from router 'glory'." },
  { kind: "LEGACY_GLORY_EXPORT_DELIVERABLE", governor: "INFRASTRUCTURE", handler: "glory", async: false, description: "Strangler-promoted mutation 'exportDeliverable' from router 'glory'." },
  { kind: "LEGACY_GUIDELINES_GENERATE", governor: "INFRASTRUCTURE", handler: "guidelines", async: false, description: "Strangler-promoted mutation 'generate' from router 'guidelines'." },
  { kind: "LEGACY_GUIDELINES_SHARE_LINK", governor: "INFRASTRUCTURE", handler: "guidelines", async: false, description: "Strangler-promoted mutation 'shareLink' from router 'guidelines'." },
  { kind: "LEGACY_GUILD_ORG_ADD_MEMBER", governor: "INFRASTRUCTURE", handler: "guild-org", async: false, description: "Strangler-promoted mutation 'addMember' from router 'guild-org'." },
  { kind: "LEGACY_GUILD_ORG_CREATE", governor: "INFRASTRUCTURE", handler: "guild-org", async: false, description: "Strangler-promoted mutation 'create' from router 'guild-org'." },
  { kind: "LEGACY_GUILD_ORG_REMOVE_MEMBER", governor: "INFRASTRUCTURE", handler: "guild-org", async: false, description: "Strangler-promoted mutation 'removeMember' from router 'guild-org'." },
  { kind: "LEGACY_GUILD_ORG_UPDATE", governor: "INFRASTRUCTURE", handler: "guild-org", async: false, description: "Strangler-promoted mutation 'update' from router 'guild-org'." },
  { kind: "LEGACY_GUILD_TIER_DEMOTE", governor: "INFRASTRUCTURE", handler: "guild-tier", async: false, description: "Strangler-promoted mutation 'demote' from router 'guild-tier'." },
  { kind: "LEGACY_GUILD_TIER_PROMOTE", governor: "INFRASTRUCTURE", handler: "guild-tier", async: false, description: "Strangler-promoted mutation 'promote' from router 'guild-tier'." },
  { kind: "LEGACY_GUILDE_ADD_PORTFOLIO_ITEM", governor: "INFRASTRUCTURE", handler: "guilde", async: false, description: "Strangler-promoted mutation 'addPortfolioItem' from router 'guilde'." },
  { kind: "LEGACY_GUILDE_ASSIGN_MENTOR", governor: "INFRASTRUCTURE", handler: "guilde", async: false, description: "Strangler-promoted mutation 'assignMentor' from router 'guilde'." },
  { kind: "LEGACY_GUILDE_REGISTER_FOR_EVENT", governor: "INFRASTRUCTURE", handler: "guilde", async: false, description: "Strangler-promoted mutation 'registerForEvent' from router 'guilde'." },
  { kind: "LEGACY_GUILDE_REMOVE_PORTFOLIO_ITEM", governor: "INFRASTRUCTURE", handler: "guilde", async: false, description: "Strangler-promoted mutation 'removePortfolioItem' from router 'guilde'." },
  { kind: "LEGACY_GUILDE_REQUEST_MENTOR", governor: "INFRASTRUCTURE", handler: "guilde", async: false, description: "Strangler-promoted mutation 'requestMentor' from router 'guilde'." },
  { kind: "LEGACY_GUILDE_REQUEST_TIER_UPGRADE", governor: "INFRASTRUCTURE", handler: "guilde", async: false, description: "Strangler-promoted mutation 'requestTierUpgrade' from router 'guilde'." },
  { kind: "LEGACY_GUILDE_UNLOCK_SKILL", governor: "INFRASTRUCTURE", handler: "guilde", async: false, description: "Strangler-promoted mutation 'unlockSkill' from router 'guilde'." },
  { kind: "LEGACY_GUILDE_UPDATE_PROFILE", governor: "INFRASTRUCTURE", handler: "guilde", async: false, description: "Strangler-promoted mutation 'updateProfile' from router 'guilde'." },
  { kind: "LEGACY_IMPLEMENTATION_GENERATOR_ACTIVATE_CAMPAIGNS", governor: "INFRASTRUCTURE", handler: "implementation-generator", async: false, description: "Strangler-promoted mutation 'activateCampaigns' from router 'implementation-generator'." },
  { kind: "LEGACY_IMPLEMENTATION_GENERATOR_GENERATE", governor: "INFRASTRUCTURE", handler: "implementation-generator", async: false, description: "Strangler-promoted mutation 'generate' from router 'implementation-generator'." },
  { kind: "LEGACY_IMPLEMENTATION_GENERATOR_REGENERATE_SECTION", governor: "INFRASTRUCTURE", handler: "implementation-generator", async: false, description: "Strangler-promoted mutation 'regenerateSection' from router 'implementation-generator'." },
  { kind: "LEGACY_INGESTION_ADD_MANUAL_SOURCE", governor: "INFRASTRUCTURE", handler: "ingestion", async: false, description: "Strangler-promoted mutation 'addManualSource' from router 'ingestion'." },
  { kind: "LEGACY_INGESTION_ADD_TEXT", governor: "INFRASTRUCTURE", handler: "ingestion", async: false, description: "Strangler-promoted mutation 'addText' from router 'ingestion'." },
  { kind: "LEGACY_INGESTION_DELETE_SOURCE", governor: "INFRASTRUCTURE", handler: "ingestion", async: false, description: "Strangler-promoted mutation 'deleteSource' from router 'ingestion'." },
  { kind: "LEGACY_INGESTION_PROCESS", governor: "INFRASTRUCTURE", handler: "ingestion", async: false, description: "Strangler-promoted mutation 'process' from router 'ingestion'." },
  { kind: "LEGACY_INGESTION_REPROCESS_PILLAR", governor: "INFRASTRUCTURE", handler: "ingestion", async: false, description: "Strangler-promoted mutation 'reprocessPillar' from router 'ingestion'." },
  { kind: "LEGACY_INGESTION_UPDATE_SOURCE", governor: "INFRASTRUCTURE", handler: "ingestion", async: false, description: "Strangler-promoted mutation 'updateSource' from router 'ingestion'." },
  { kind: "LEGACY_INGESTION_UPLOAD_FILE", governor: "INFRASTRUCTURE", handler: "ingestion", async: false, description: "Strangler-promoted mutation 'uploadFile' from router 'ingestion'." },
  { kind: "LEGACY_INGESTION_VALIDATE_PILLAR", governor: "INFRASTRUCTURE", handler: "ingestion", async: false, description: "Strangler-promoted mutation 'validatePillar' from router 'ingestion'." },
  { kind: "LEGACY_INTERVENTION_CONVERT_TO_MISSION", governor: "INFRASTRUCTURE", handler: "intervention", async: false, description: "Strangler-promoted mutation 'convertToMission' from router 'intervention'." },
  { kind: "LEGACY_INTERVENTION_CREATE", governor: "INFRASTRUCTURE", handler: "intervention", async: false, description: "Strangler-promoted mutation 'create' from router 'intervention'." },
  { kind: "LEGACY_INTERVENTION_DISMISS", governor: "INFRASTRUCTURE", handler: "intervention", async: false, description: "Strangler-promoted mutation 'dismiss' from router 'intervention'." },
  { kind: "LEGACY_KNOWLEDGE_GRAPH_INGEST", governor: "INFRASTRUCTURE", handler: "knowledge-graph", async: false, description: "Strangler-promoted mutation 'ingest' from router 'knowledge-graph'." },
  { kind: "LEGACY_LEARNING_CREATE_COURSE", governor: "INFRASTRUCTURE", handler: "learning", async: false, description: "Strangler-promoted mutation 'createCourse' from router 'learning'." },
  { kind: "LEGACY_LEARNING_ENROLL", governor: "INFRASTRUCTURE", handler: "learning", async: false, description: "Strangler-promoted mutation 'enroll' from router 'learning'." },
  { kind: "LEGACY_LEARNING_ISSUE_CERTIFICATION", governor: "INFRASTRUCTURE", handler: "learning", async: false, description: "Strangler-promoted mutation 'issueCertification' from router 'learning'." },
  { kind: "LEGACY_LEARNING_PUBLISH_COURSE", governor: "INFRASTRUCTURE", handler: "learning", async: false, description: "Strangler-promoted mutation 'publishCourse' from router 'learning'." },
  { kind: "LEGACY_LEARNING_UPDATE_PROGRESS", governor: "INFRASTRUCTURE", handler: "learning", async: false, description: "Strangler-promoted mutation 'updateProgress' from router 'learning'." },
  { kind: "LEGACY_MARKET_INTELLIGENCE_COLLECT_NOW", governor: "INFRASTRUCTURE", handler: "market-intelligence", async: false, description: "Strangler-promoted mutation 'collectNow' from router 'market-intelligence'." },
  { kind: "LEGACY_MARKET_INTELLIGENCE_INGEST_SIGNAL", governor: "INFRASTRUCTURE", handler: "market-intelligence", async: false, description: "Strangler-promoted mutation 'ingestSignal' from router 'market-intelligence'." },
  { kind: "LEGACY_MARKET_INTELLIGENCE_REGISTER_COLLECTOR", governor: "INFRASTRUCTURE", handler: "market-intelligence", async: false, description: "Strangler-promoted mutation 'registerCollector' from router 'market-intelligence'." },
  { kind: "LEGACY_MARKET_INTELLIGENCE_RUN", governor: "INFRASTRUCTURE", handler: "market-intelligence", async: false, description: "Strangler-promoted mutation 'run' from router 'market-intelligence'." },
  { kind: "LEGACY_MARKET_INTELLIGENCE_STOP_COLLECTOR", governor: "INFRASTRUCTURE", handler: "market-intelligence", async: false, description: "Strangler-promoted mutation 'stopCollector' from router 'market-intelligence'." },
  { kind: "LEGACY_MARKET_STUDY_CREATE", governor: "INFRASTRUCTURE", handler: "market-study", async: false, description: "Strangler-promoted mutation 'create' from router 'market-study'." },
  { kind: "LEGACY_MATCHING_OVERRIDE", governor: "INFRASTRUCTURE", handler: "matching", async: false, description: "Strangler-promoted mutation 'override' from router 'matching'." },
  { kind: "LEGACY_MEDIA_BUYING_DETECT_ANOMALIES", governor: "INFRASTRUCTURE", handler: "media-buying", async: false, description: "Strangler-promoted mutation 'detectAnomalies' from router 'media-buying'." },
  { kind: "LEGACY_MEDIA_BUYING_PUSH_BENCHMARKS", governor: "INFRASTRUCTURE", handler: "media-buying", async: false, description: "Strangler-promoted mutation 'pushBenchmarks' from router 'media-buying'." },
  { kind: "LEGACY_MEDIA_BUYING_SYNC_TO_CAMPAIGN", governor: "INFRASTRUCTURE", handler: "media-buying", async: false, description: "Strangler-promoted mutation 'syncToCampaign' from router 'media-buying'." },
  { kind: "LEGACY_MEMBERSHIP_CANCEL", governor: "INFRASTRUCTURE", handler: "membership", async: false, description: "Strangler-promoted mutation 'cancel' from router 'membership'." },
  { kind: "LEGACY_MEMBERSHIP_CREATE", governor: "INFRASTRUCTURE", handler: "membership", async: false, description: "Strangler-promoted mutation 'create' from router 'membership'." },
  { kind: "LEGACY_MEMBERSHIP_RENEW", governor: "INFRASTRUCTURE", handler: "membership", async: false, description: "Strangler-promoted mutation 'renew' from router 'membership'." },
  { kind: "LEGACY_MESSAGING_MARK_AS_READ", governor: "INFRASTRUCTURE", handler: "messaging", async: false, description: "Strangler-promoted mutation 'markAsRead' from router 'messaging'." },
  { kind: "LEGACY_MESSAGING_SEED_DEMO", governor: "INFRASTRUCTURE", handler: "messaging", async: false, description: "Strangler-promoted mutation 'seedDemo' from router 'messaging'." },
  { kind: "LEGACY_MESSAGING_SEND_MESSAGE", governor: "INFRASTRUCTURE", handler: "messaging", async: false, description: "Strangler-promoted mutation 'sendMessage' from router 'messaging'." },
  { kind: "LEGACY_MESTOR_ROUTER_CHAT", governor: "INFRASTRUCTURE", handler: "mestor-router", async: false, description: "Strangler-promoted mutation 'chat' from router 'mestor-router'." },
  { kind: "LEGACY_MESTOR_ROUTER_INPUT_SCHEMA", governor: "INFRASTRUCTURE", handler: "mestor-router", async: false, description: "Strangler-promoted mutation 'inputSchema' from router 'mestor-router'." },
  { kind: "LEGACY_MESTOR_ROUTER_RESOLVE_STEP", governor: "INFRASTRUCTURE", handler: "mestor-router", async: false, description: "Strangler-promoted mutation 'resolveStep' from router 'mestor-router'." },
  { kind: "LEGACY_MESTOR_ROUTER_RESUME_PLAN", governor: "INFRASTRUCTURE", handler: "mestor-router", async: false, description: "Strangler-promoted mutation 'resumePlan' from router 'mestor-router'." },
  { kind: "LEGACY_MISSION_ACCEPT_DELIVERABLE", governor: "INFRASTRUCTURE", handler: "mission", async: false, description: "Strangler-promoted mutation 'acceptDeliverable' from router 'mission'." },
  { kind: "LEGACY_MISSION_ASSIGN", governor: "INFRASTRUCTURE", handler: "mission", async: false, description: "Strangler-promoted mutation 'assign' from router 'mission'." },
  { kind: "LEGACY_MISSION_CLAIM", governor: "INFRASTRUCTURE", handler: "mission", async: false, description: "Strangler-promoted mutation 'claim' from router 'mission'." },
  { kind: "LEGACY_MISSION_DELETE", governor: "INFRASTRUCTURE", handler: "mission", async: false, description: "Strangler-promoted mutation 'delete' from router 'mission'." },
  { kind: "LEGACY_MISSION_REVIEW_DELIVERABLE", governor: "INFRASTRUCTURE", handler: "mission", async: false, description: "Strangler-promoted mutation 'reviewDeliverable' from router 'mission'." },
  { kind: "LEGACY_MISSION_SET_DEADLINE", governor: "INFRASTRUCTURE", handler: "mission", async: false, description: "Strangler-promoted mutation 'setDeadline' from router 'mission'." },
  { kind: "LEGACY_MISSION_SUBMIT_DELIVERABLE", governor: "INFRASTRUCTURE", handler: "mission", async: false, description: "Strangler-promoted mutation 'submitDeliverable' from router 'mission'." },
  { kind: "LEGACY_MOBILE_MONEY_INITIATE_PAYMENT", governor: "INFRASTRUCTURE", handler: "mobile-money", async: false, description: "Strangler-promoted mutation 'initiatePayment' from router 'mobile-money'." },
  { kind: "LEGACY_MOBILE_MONEY_PAY_COMMISSION", governor: "INFRASTRUCTURE", handler: "mobile-money", async: false, description: "Strangler-promoted mutation 'payCommission' from router 'mobile-money'." },
  { kind: "LEGACY_MOBILE_MONEY_WEBHOOK", governor: "INFRASTRUCTURE", handler: "mobile-money", async: false, description: "Strangler-promoted mutation 'webhook' from router 'mobile-money'." },
  { kind: "LEGACY_MONETIZATION_ADMIN_DELETE_OVERRIDE", governor: "INFRASTRUCTURE", handler: "monetization", async: false, description: "Strangler-promoted mutation 'adminDeleteOverride' from router 'monetization'." },
  { kind: "LEGACY_MONETIZATION_ADMIN_UPDATE_PROVIDER_CONFIG", governor: "INFRASTRUCTURE", handler: "monetization", async: false, description: "Strangler-promoted mutation 'adminUpdateProviderConfig' from router 'monetization'." },
  { kind: "LEGACY_MONETIZATION_ADMIN_UPSERT_OVERRIDE", governor: "INFRASTRUCTURE", handler: "monetization", async: false, description: "Strangler-promoted mutation 'adminUpsertOverride' from router 'monetization'." },
  { kind: "LEGACY_MONETIZATION_CANCEL_SUBSCRIPTION", governor: "INFRASTRUCTURE", handler: "monetization", async: false, description: "Strangler-promoted mutation 'cancelSubscription' from router 'monetization'." },
  { kind: "LEGACY_MONETIZATION_INIT_SUBSCRIPTION", governor: "INFRASTRUCTURE", handler: "monetization", async: false, description: "Strangler-promoted mutation 'initSubscription' from router 'monetization'." },
  { kind: "LEGACY_NOTIFICATION_CREATE", governor: "INFRASTRUCTURE", handler: "notification", async: false, description: "Strangler-promoted mutation 'create' from router 'notification'." },
  { kind: "LEGACY_NOTIFICATION_MARK_ALL_READ", governor: "INFRASTRUCTURE", handler: "notification", async: false, description: "Strangler-promoted mutation 'markAllRead' from router 'notification'." },
  { kind: "LEGACY_NOTIFICATION_MARK_READ", governor: "INFRASTRUCTURE", handler: "notification", async: false, description: "Strangler-promoted mutation 'markRead' from router 'notification'." },
  { kind: "LEGACY_NOTIFICATION_UPDATE_PREFERENCES", governor: "INFRASTRUCTURE", handler: "notification", async: false, description: "Strangler-promoted mutation 'updatePreferences' from router 'notification'." },
  { kind: "LEGACY_NOTORIA_ACCEPT_RECOS", governor: "INFRASTRUCTURE", handler: "notoria", async: false, description: "Strangler-promoted mutation 'acceptRecos' from router 'notoria'." },
  { kind: "LEGACY_NOTORIA_ACTUALIZE_R_T", governor: "INFRASTRUCTURE", handler: "notoria", async: false, description: "Strangler-promoted mutation 'actualizeRT' from router 'notoria'." },
  { kind: "LEGACY_NOTORIA_ADVANCE_PIPELINE", governor: "INFRASTRUCTURE", handler: "notoria", async: false, description: "Strangler-promoted mutation 'advancePipeline' from router 'notoria'." },
  { kind: "LEGACY_NOTORIA_APPLY_BATCH", governor: "INFRASTRUCTURE", handler: "notoria", async: false, description: "Strangler-promoted mutation 'applyBatch' from router 'notoria'." },
  { kind: "LEGACY_NOTORIA_APPLY_RECOS", governor: "INFRASTRUCTURE", handler: "notoria", async: false, description: "Strangler-promoted mutation 'applyRecos' from router 'notoria'." },
  { kind: "LEGACY_NOTORIA_EXPIRE_OLD_RECOS", governor: "INFRASTRUCTURE", handler: "notoria", async: false, description: "Strangler-promoted mutation 'expireOldRecos' from router 'notoria'." },
  { kind: "LEGACY_NOTORIA_LAUNCH_PIPELINE", governor: "INFRASTRUCTURE", handler: "notoria", async: false, description: "Strangler-promoted mutation 'launchPipeline' from router 'notoria'." },
  { kind: "LEGACY_NOTORIA_PRECONDITIONS", governor: "INFRASTRUCTURE", handler: "notoria", async: false, description: "Strangler-promoted mutation 'preconditions' from router 'notoria'." },
  { kind: "LEGACY_NOTORIA_PUBLISH_TO_JEHUTY", governor: "INFRASTRUCTURE", handler: "notoria", async: false, description: "Strangler-promoted mutation 'publishToJehuty' from router 'notoria'." },
  { kind: "LEGACY_NOTORIA_REJECT_RECOS", governor: "INFRASTRUCTURE", handler: "notoria", async: false, description: "Strangler-promoted mutation 'rejectRecos' from router 'notoria'." },
  { kind: "LEGACY_NOTORIA_REVERT_RECO", governor: "INFRASTRUCTURE", handler: "notoria", async: false, description: "Strangler-promoted mutation 'revertReco' from router 'notoria'." },
  { kind: "LEGACY_ONBOARDING_ADVANCE", governor: "INFRASTRUCTURE", handler: "onboarding", async: false, description: "Strangler-promoted mutation 'advance' from router 'onboarding'." },
  { kind: "LEGACY_ONBOARDING_COMPLETE", governor: "INFRASTRUCTURE", handler: "onboarding", async: false, description: "Strangler-promoted mutation 'complete' from router 'onboarding'." },
  { kind: "LEGACY_ONBOARDING_START", governor: "INFRASTRUCTURE", handler: "onboarding", async: false, description: "Strangler-promoted mutation 'start' from router 'onboarding'." },
  { kind: "LEGACY_OPERATOR_ALLOCATE_CLIENT", governor: "INFRASTRUCTURE", handler: "operator", async: false, description: "Strangler-promoted mutation 'allocateClient' from router 'operator'." },
  { kind: "LEGACY_OPERATOR_DEALLOCATE_CLIENT", governor: "INFRASTRUCTURE", handler: "operator", async: false, description: "Strangler-promoted mutation 'deallocateClient' from router 'operator'." },
  { kind: "LEGACY_OPERATOR_REACTIVATE", governor: "INFRASTRUCTURE", handler: "operator", async: false, description: "Strangler-promoted mutation 'reactivate' from router 'operator'." },
  { kind: "LEGACY_OPERATOR_SUSPEND", governor: "INFRASTRUCTURE", handler: "operator", async: false, description: "Strangler-promoted mutation 'suspend' from router 'operator'." },
  { kind: "LEGACY_PILLAR_ACCEPT_RECOS", governor: "INFRASTRUCTURE", handler: "pillar", async: false, description: "Strangler-promoted mutation 'acceptRecos' from router 'pillar'." },
  { kind: "LEGACY_PILLAR_ACTUALIZE", governor: "INFRASTRUCTURE", handler: "pillar", async: false, description: "Strangler-promoted mutation 'actualize' from router 'pillar'." },
  { kind: "LEGACY_PILLAR_ADD_PERSONA", governor: "INFRASTRUCTURE", handler: "pillar", async: false, description: "Strangler-promoted mutation 'addPersona' from router 'pillar'." },
  { kind: "LEGACY_PILLAR_ADD_PRODUCT", governor: "INFRASTRUCTURE", handler: "pillar", async: false, description: "Strangler-promoted mutation 'addProduct' from router 'pillar'." },
  { kind: "LEGACY_PILLAR_ADD_RITUAL", governor: "INFRASTRUCTURE", handler: "pillar", async: false, description: "Strangler-promoted mutation 'addRitual' from router 'pillar'." },
  { kind: "LEGACY_PILLAR_ADD_TOUCHPOINT", governor: "INFRASTRUCTURE", handler: "pillar", async: false, description: "Strangler-promoted mutation 'addTouchpoint' from router 'pillar'." },
  { kind: "LEGACY_PILLAR_ADD_VALUE", governor: "INFRASTRUCTURE", handler: "pillar", async: false, description: "Strangler-promoted mutation 'addValue' from router 'pillar'." },
  { kind: "LEGACY_PILLAR_APPLY_GLORY_OUTPUT", governor: "INFRASTRUCTURE", handler: "pillar", async: false, description: "Strangler-promoted mutation 'applyGloryOutput' from router 'pillar'." },
  { kind: "LEGACY_PILLAR_AUTO_FILL", governor: "INFRASTRUCTURE", handler: "pillar", async: false, description: "Strangler-promoted mutation 'autoFill' from router 'pillar'." },
  { kind: "LEGACY_PILLAR_AUTO_FILL_ALL", governor: "INFRASTRUCTURE", handler: "pillar", async: false, description: "Strangler-promoted mutation 'autoFillAll' from router 'pillar'." },
  { kind: "LEGACY_PILLAR_ENRICH_ALL_FROM_VAULT", governor: "INFRASTRUCTURE", handler: "pillar", async: false, description: "Strangler-promoted mutation 'enrichAllFromVault' from router 'pillar'." },
  { kind: "LEGACY_PILLAR_ENRICH_FROM_VAULT", governor: "INFRASTRUCTURE", handler: "pillar", async: false, description: "Strangler-promoted mutation 'enrichFromVault' from router 'pillar'." },
  { kind: "LEGACY_PILLAR_GENERATE_RECOS", governor: "INFRASTRUCTURE", handler: "pillar", async: false, description: "Strangler-promoted mutation 'generateRecos' from router 'pillar'." },
  { kind: "LEGACY_PILLAR_INPUT_SCHEMA", governor: "INFRASTRUCTURE", handler: "pillar", async: false, description: "Strangler-promoted mutation 'inputSchema' from router 'pillar'." },
  { kind: "LEGACY_PILLAR_REJECT_RECOS", governor: "INFRASTRUCTURE", handler: "pillar", async: false, description: "Strangler-promoted mutation 'rejectRecos' from router 'pillar'." },
  { kind: "LEGACY_PILLAR_ROLLBACK_VERSION", governor: "INFRASTRUCTURE", handler: "pillar", async: false, description: "Strangler-promoted mutation 'rollbackVersion' from router 'pillar'." },
  { kind: "LEGACY_PILLAR_TRANSITION_PHASE", governor: "INFRASTRUCTURE", handler: "pillar", async: false, description: "Strangler-promoted mutation 'transitionPhase' from router 'pillar'." },
  { kind: "LEGACY_PILLAR_TRANSITION_STATUS", governor: "INFRASTRUCTURE", handler: "pillar", async: false, description: "Strangler-promoted mutation 'transitionStatus' from router 'pillar'." },
  { kind: "LEGACY_PILLAR_UPDATE_COMMENTARY", governor: "INFRASTRUCTURE", handler: "pillar", async: false, description: "Strangler-promoted mutation 'updateCommentary' from router 'pillar'." },
  { kind: "LEGACY_PR_CREATE_RELEASE", governor: "INFRASTRUCTURE", handler: "pr", async: false, description: "Strangler-promoted mutation 'createRelease' from router 'pr'." },
  { kind: "LEGACY_PR_INGEST_CLIPPING", governor: "INFRASTRUCTURE", handler: "pr", async: false, description: "Strangler-promoted mutation 'ingestClipping' from router 'pr'." },
  { kind: "LEGACY_PR_PROCESS_CLIPPING", governor: "INFRASTRUCTURE", handler: "pr", async: false, description: "Strangler-promoted mutation 'processClipping' from router 'pr'." },
  { kind: "LEGACY_PR_SCORE_PRESS_RELEASE", governor: "INFRASTRUCTURE", handler: "pr", async: false, description: "Strangler-promoted mutation 'scorePressRelease' from router 'pr'." },
  { kind: "LEGACY_PR_TRACK_DISTRIBUTION", governor: "INFRASTRUCTURE", handler: "pr", async: false, description: "Strangler-promoted mutation 'trackDistribution' from router 'pr'." },
  { kind: "LEGACY_PROCESS_CREATE", governor: "INFRASTRUCTURE", handler: "process", async: false, description: "Strangler-promoted mutation 'create' from router 'process'." },
  { kind: "LEGACY_PROCESS_DELETE", governor: "INFRASTRUCTURE", handler: "process", async: false, description: "Strangler-promoted mutation 'delete' from router 'process'." },
  { kind: "LEGACY_PROCESS_PAUSE", governor: "INFRASTRUCTURE", handler: "process", async: false, description: "Strangler-promoted mutation 'pause' from router 'process'." },
  { kind: "LEGACY_PROCESS_RUN_BATCH", governor: "INFRASTRUCTURE", handler: "process", async: false, description: "Strangler-promoted mutation 'runBatch' from router 'process'." },
  { kind: "LEGACY_PROCESS_SCHEDULE_DAEMON", governor: "INFRASTRUCTURE", handler: "process", async: false, description: "Strangler-promoted mutation 'scheduleDaemon' from router 'process'." },
  { kind: "LEGACY_PROCESS_START", governor: "INFRASTRUCTURE", handler: "process", async: false, description: "Strangler-promoted mutation 'start' from router 'process'." },
  { kind: "LEGACY_PROCESS_STOP", governor: "INFRASTRUCTURE", handler: "process", async: false, description: "Strangler-promoted mutation 'stop' from router 'process'." },
  { kind: "LEGACY_PROCESS_TRIGGER_ON_SIGNAL", governor: "INFRASTRUCTURE", handler: "process", async: false, description: "Strangler-promoted mutation 'triggerOnSignal' from router 'process'." },
  { kind: "LEGACY_PROCESS_UPDATE", governor: "INFRASTRUCTURE", handler: "process", async: false, description: "Strangler-promoted mutation 'update' from router 'process'." },
  { kind: "LEGACY_PUBLICATION_DELETE", governor: "INFRASTRUCTURE", handler: "publication", async: false, description: "Strangler-promoted mutation 'delete' from router 'publication'." },
  { kind: "LEGACY_QUALITY_REVIEW_ASSIGN_REVIEWER", governor: "INFRASTRUCTURE", handler: "quality-review", async: false, description: "Strangler-promoted mutation 'assignReviewer' from router 'quality-review'." },
  { kind: "LEGACY_QUALITY_REVIEW_ESCALATE", governor: "INFRASTRUCTURE", handler: "quality-review", async: false, description: "Strangler-promoted mutation 'escalate' from router 'quality-review'." },
  { kind: "LEGACY_QUALITY_REVIEW_SUBMIT", governor: "INFRASTRUCTURE", handler: "quality-review", async: false, description: "Strangler-promoted mutation 'submit' from router 'quality-review'." },
  { kind: "LEGACY_QUICK_INTAKE_ACTIVATE_BRAND", governor: "INFRASTRUCTURE", handler: "quick-intake", async: false, description: "Strangler-promoted mutation 'activateBrand' from router 'quick-intake'." },
  { kind: "LEGACY_QUICK_INTAKE_COMPLETE", governor: "INFRASTRUCTURE", handler: "quick-intake", async: false, description: "Strangler-promoted mutation 'complete' from router 'quick-intake'." },
  { kind: "LEGACY_QUICK_INTAKE_CONVERT", governor: "INFRASTRUCTURE", handler: "quick-intake", async: false, description: "Strangler-promoted mutation 'convert' from router 'quick-intake'." },
  { kind: "LEGACY_QUICK_INTAKE_EXPIRE_STALE", governor: "INFRASTRUCTURE", handler: "quick-intake", async: false, description: "Strangler-promoted mutation 'expireStale' from router 'quick-intake'." },
  { kind: "LEGACY_QUICK_INTAKE_NOTIFY_FIXER_ON_COMPLETE", governor: "INFRASTRUCTURE", handler: "quick-intake", async: false, description: "Strangler-promoted mutation 'notifyFixerOnComplete' from router 'quick-intake'." },
  { kind: "LEGACY_QUICK_INTAKE_PROCESS_INGEST", governor: "INFRASTRUCTURE", handler: "quick-intake", async: false, description: "Strangler-promoted mutation 'processIngest' from router 'quick-intake'." },
  { kind: "LEGACY_QUICK_INTAKE_PROCESS_INGEST_PLUS", governor: "INFRASTRUCTURE", handler: "quick-intake", async: false, description: "Strangler-promoted mutation 'processIngestPlus' from router 'quick-intake'." },
  { kind: "LEGACY_QUICK_INTAKE_PROCESS_SHORT", governor: "INFRASTRUCTURE", handler: "quick-intake", async: false, description: "Strangler-promoted mutation 'processShort' from router 'quick-intake'." },
  { kind: "LEGACY_SEQUENCE_VAULT_ACCEPT", governor: "INFRASTRUCTURE", handler: "sequence-vault", async: false, description: "Strangler-promoted mutation 'accept' from router 'sequence-vault'." },
  { kind: "LEGACY_SEQUENCE_VAULT_DELETE", governor: "INFRASTRUCTURE", handler: "sequence-vault", async: false, description: "Strangler-promoted mutation 'delete' from router 'sequence-vault'." },
  { kind: "LEGACY_SEQUENCE_VAULT_REJECT", governor: "INFRASTRUCTURE", handler: "sequence-vault", async: false, description: "Strangler-promoted mutation 'reject' from router 'sequence-vault'." },
  { kind: "LEGACY_SIGNAL_CONFIGURE_THRESHOLDS", governor: "INFRASTRUCTURE", handler: "signal", async: false, description: "Strangler-promoted mutation 'configureThresholds' from router 'signal'." },
  { kind: "LEGACY_SIGNAL_CREATE", governor: "INFRASTRUCTURE", handler: "signal", async: false, description: "Strangler-promoted mutation 'create' from router 'signal'." },
  { kind: "LEGACY_SIGNAL_INGEST_SOCIAL_METRICS", governor: "INFRASTRUCTURE", handler: "signal", async: false, description: "Strangler-promoted mutation 'ingestSocialMetrics' from router 'signal'." },
  { kind: "LEGACY_SIGNAL_PROPAGATE_TO_QUEUE", governor: "INFRASTRUCTURE", handler: "signal", async: false, description: "Strangler-promoted mutation 'propagateToQueue' from router 'signal'." },
  { kind: "LEGACY_SIGNAL_REPROCESS", governor: "INFRASTRUCTURE", handler: "signal", async: false, description: "Strangler-promoted mutation 'reprocess' from router 'signal'." },
  { kind: "LEGACY_SOCIAL_CONNECT_TO_DRIVER", governor: "INFRASTRUCTURE", handler: "social", async: false, description: "Strangler-promoted mutation 'connectToDriver' from router 'social'." },
  { kind: "LEGACY_SOCIAL_LINK_TO_DRIVER", governor: "INFRASTRUCTURE", handler: "social", async: false, description: "Strangler-promoted mutation 'linkToDriver' from router 'social'." },
  { kind: "LEGACY_SOCIAL_PROCESS_METRICS", governor: "INFRASTRUCTURE", handler: "social", async: false, description: "Strangler-promoted mutation 'processMetrics' from router 'social'." },
  { kind: "LEGACY_STALENESS_AUDIT_ALL", governor: "INFRASTRUCTURE", handler: "staleness", async: false, description: "Strangler-promoted mutation 'auditAll' from router 'staleness'." },
  { kind: "LEGACY_STALENESS_PROPAGATE", governor: "INFRASTRUCTURE", handler: "staleness", async: false, description: "Strangler-promoted mutation 'propagate' from router 'staleness'." },
  { kind: "LEGACY_STALENESS_UPDATE_CONFIG", governor: "INFRASTRUCTURE", handler: "staleness", async: false, description: "Strangler-promoted mutation 'updateConfig' from router 'staleness'." },
  { kind: "LEGACY_STRATEGY_CREATE", governor: "INFRASTRUCTURE", handler: "strategy", async: false, description: "Strangler-promoted mutation 'create' from router 'strategy'." },
  { kind: "LEGACY_STRATEGY_DELETE", governor: "INFRASTRUCTURE", handler: "strategy", async: false, description: "Strangler-promoted mutation 'delete' from router 'strategy'." },
  { kind: "LEGACY_STRATEGY_MIGRATE_TO_V4", governor: "INFRASTRUCTURE", handler: "strategy", async: false, description: "Strangler-promoted mutation 'migrateToV4' from router 'strategy'." },
  { kind: "LEGACY_STRATEGY_PRESENTATION_PRECONDITIONS", governor: "INFRASTRUCTURE", handler: "strategy-presentation", async: false, description: "Strangler-promoted mutation 'preconditions' from router 'strategy-presentation'." },
  { kind: "LEGACY_STRATEGY_PRESENTATION_SHARE_LINK", governor: "INFRASTRUCTURE", handler: "strategy-presentation", async: false, description: "Strangler-promoted mutation 'shareLink' from router 'strategy-presentation'." },
  { kind: "LEGACY_STRATEGY_UPDATE", governor: "INFRASTRUCTURE", handler: "strategy", async: false, description: "Strangler-promoted mutation 'update' from router 'strategy'." },
  { kind: "LEGACY_SYSTEM_CONFIG_UPSERT", governor: "INFRASTRUCTURE", handler: "system-config", async: false, description: "Strangler-promoted mutation 'upsert' from router 'system-config'." },
  { kind: "LEGACY_TRANSLATION_CREATE", governor: "INFRASTRUCTURE", handler: "translation", async: false, description: "Strangler-promoted mutation 'create' from router 'translation'." },
  { kind: "LEGACY_UPSELL_DISMISS", governor: "INFRASTRUCTURE", handler: "upsell", async: false, description: "Strangler-promoted mutation 'dismiss' from router 'upsell'." },
  // ── /AUTOGEN: legacy-intent-kinds ──
] as const;

export const INTENT_KIND_BY_NAME = new Map(INTENT_KINDS.map((k) => [k.kind, k]));

export function intentKindExists(name: string): boolean {
  return INTENT_KIND_BY_NAME.has(name);
}
