/**
 * registry.generated.ts — Aggregated manifest registry.
 *
 * This file is REGENERATED by `npm run manifests:gen` (which globs all
 * services/manifest.ts files and re-exports them). Do not edit by hand.
 *
 * Type-safe consumption:
 *   import { ALL_MANIFESTS, getManifest } from "@/server/governance/registry.generated";
 *
 * Currently maintained as a pass-through to the existing registry.ts so
 * existing code keeps working. Full codegen wires up in P2 final.
 */

import type { NeteruManifest } from "./manifest";
import * as governanceRegistry from "./registry";

// ── Static manifest list (manually maintained until codegen lands) ───
// The dynamic registration via boot-sequence in registry.ts populates
// the list at runtime; here we re-export accessor functions.

export const ALL_MANIFESTS = (): readonly NeteruManifest[] => {
  // governanceRegistry.GOVERNANCE_REGISTRY is populated by services that
  // self-register at boot. For tooling/audit that runs before boot
  // (e.g. CI), use scripts/audit-manifests.ts which globs FS instead.
  const reg = (governanceRegistry as unknown as { ALL?: readonly NeteruManifest[] }).ALL;
  return reg ?? [];
};

export function getManifest(serviceSlug: string): NeteruManifest | undefined {
  return ALL_MANIFESTS().find((m) => m.service === serviceSlug);
}

export function findHandlerForIntent(kind: string): NeteruManifest | undefined {
  return ALL_MANIFESTS().find((m) => m.acceptsIntents?.includes(kind));
}

export function listEmittedIntents(): readonly string[] {
  const set = new Set<string>();
  for (const m of ALL_MANIFESTS()) {
    for (const k of m.emits ?? []) set.add(k);
  }
  return Array.from(set).sort();
}

export function listAcceptedIntents(): readonly string[] {
  const set = new Set<string>();
  for (const m of ALL_MANIFESTS()) {
    for (const k of m.acceptsIntents ?? []) set.add(k);
  }
  return Array.from(set).sort();
}
