/**
 * src/server/governance/registry.ts — Runtime manifest registry.
 *
 * Layer 2. Aggregates every `manifest.ts` discovered under
 * src/server/services/ (via the codegen `__generated__/manifest-imports.ts`,
 * regenerated by `npm run manifests:gen`).
 *
 * Public API:
 *   - getManifest(service): NeteruManifest | undefined
 *   - getAllManifests(): readonly NeteruManifest[]
 *   - getServicesByGovernor(brain): readonly string[]
 *   - findCapability(intentKind): { service, capability } | undefined
 *   - auditManifests(): { ok, issues }
 */

import type { Brain, NeteruManifest } from "./manifest";
import { MANIFESTS } from "./__generated__/manifest-imports";

const BY_SERVICE = new Map<string, NeteruManifest>();
const BY_INTENT = new Map<string, { service: string; capability: string }>();

for (const m of MANIFESTS) {
  if (BY_SERVICE.has(m.service)) {
    throw new Error(
      `Duplicate manifest for service '${m.service}'. Each service must have at most one manifest.ts.`,
    );
  }
  BY_SERVICE.set(m.service, m);
  for (const intent of m.acceptsIntents ?? []) {
    if (BY_INTENT.has(intent)) {
      const prev = BY_INTENT.get(intent)!;
      throw new Error(
        `Intent kind '${intent}' is accepted by both '${prev.service}' and '${m.service}'. ` +
          `Each Intent kind must have exactly one accepting service.`,
      );
    }
    // Pick the first capability — granular dispatch handled by Mestor.
    const firstCap = m.capabilities[0];
    BY_INTENT.set(intent, {
      service: m.service,
      capability: firstCap?.name ?? intent,
    });
  }
}

export const getManifest = (service: string): NeteruManifest | undefined =>
  BY_SERVICE.get(service);

export const getAllManifests = (): readonly NeteruManifest[] =>
  Array.from(BY_SERVICE.values());

export const getServicesByGovernor = (brain: Brain): readonly string[] =>
  getAllManifests()
    .filter((m) => m.governor === brain)
    .map((m) => m.service);

export const findCapability = (
  intentKind: string,
): { service: string; capability: string } | undefined =>
  BY_INTENT.get(intentKind);

export interface ManifestAuditResult {
  readonly ok: boolean;
  readonly count: number;
  readonly issues: readonly string[];
}

export function auditManifests(): ManifestAuditResult {
  const issues: string[] = [];
  for (const m of getAllManifests()) {
    if (!/^\d+\.\d+\.\d+$/.test(m.version)) {
      issues.push(`${m.service}: version '${m.version}' is not semver`);
    }
    for (const cap of m.capabilities) {
      if (!cap.name) issues.push(`${m.service}: capability missing name`);
    }
    for (const dep of m.dependencies ?? []) {
      if (!BY_SERVICE.has(dep)) {
        issues.push(`${m.service}: dependency '${dep}' has no manifest`);
      }
    }
  }
  return {
    ok: issues.length === 0,
    count: BY_SERVICE.size,
    issues,
  };
}
