/**
 * scripts/gen-manifest-registry.ts — Codegen for the manifest registry.
 *
 * Run: `npm run manifests:gen`.
 * Output: src/server/governance/__generated__/manifest-imports.ts (committed).
 *
 * Discovers `src/server/services/<slug>/manifest.ts` files and emits a
 * static import list. Static imports keep Next.js build fast and the
 * registry tree-shakeable.
 */

import { promises as fs } from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SERVICES_DIR = path.join(ROOT, "src", "server", "services");
const OUT_FILE = path.join(
  ROOT,
  "src",
  "server",
  "governance",
  "__generated__",
  "manifest-imports.ts",
);

function camelCase(slug: string): string {
  return slug
    .replace(/[-_](.)/g, (_, c) => c.toUpperCase())
    .replace(/^./, (c) => c.toLowerCase());
}

async function findManifests(dir: string, base = ""): Promise<string[]> {
  const found: string[] = [];
  let entries;
  try {
    entries = await fs.readdir(dir, { withFileTypes: true });
  } catch {
    return found;
  }
  for (const e of entries) {
    if (!e.isDirectory()) continue;
    if (e.name.startsWith(".")) continue;
    if (/\s\d+$/.test(e.name)) continue; // skip numbered duplicates
    const sub = path.join(dir, e.name);
    const manifestPath = path.join(sub, "manifest.ts");
    try {
      await fs.access(manifestPath);
      found.push(path.posix.join(base, e.name));
    } catch {
      // recurse one level deeper for nested services (e.g. seshat/tarsis)
      const subSub = await fs.readdir(sub, { withFileTypes: true });
      for (const s of subSub) {
        if (!s.isDirectory()) continue;
        const nested = path.join(sub, s.name, "manifest.ts");
        try {
          await fs.access(nested);
          found.push(path.posix.join(base, e.name, s.name));
        } catch {
          /* none */
        }
      }
    }
  }
  return found;
}

async function main() {
  const slugs = await findManifests(SERVICES_DIR);
  slugs.sort();

  const lines: string[] = [];
  lines.push("/**");
  lines.push(" * AUTO-GENERATED — do not edit by hand.");
  lines.push(" * Generated by `npm run manifests:gen` (scripts/gen-manifest-registry.ts).");
  lines.push(" */");
  lines.push("");
  lines.push('import type { NeteruManifest } from "../manifest";');
  lines.push("");

  const aliases: string[] = [];
  for (const slug of slugs) {
    const last = slug.split("/").pop()!;
    const alias = `${camelCase(last)}Manifest`;
    aliases.push(alias);
    lines.push(
      `import { manifest as ${alias} } from "@/server/services/${slug}/manifest";`,
    );
  }
  lines.push("");
  lines.push("export const MANIFESTS: readonly NeteruManifest[] = [");
  for (const alias of aliases) lines.push(`  ${alias},`);
  lines.push("];");
  lines.push("");

  await fs.writeFile(OUT_FILE, lines.join("\n"), "utf8");
  console.log(`Wrote ${OUT_FILE} with ${slugs.length} manifest(s).`);
  for (const s of slugs) console.log(`  - ${s}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
