/**
 * scripts/gen-intent-catalog.ts — emits docs/governance/INTENT-CATALOG.md
 * from the runtime registry + INTENT_KINDS catalog. Run as part of CI to
 * keep docs in sync (Phase 8).
 */

import { promises as fs } from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import { INTENT_KINDS } from "@/server/governance/intent-kinds";
import { SLO_BY_KIND } from "@/server/governance/slos";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUT = path.join(ROOT, "docs", "governance", "INTENT-CATALOG.md");

async function main() {
  const lines: string[] = [];
  lines.push("# Intent Catalog");
  lines.push("");
  lines.push(
    "Auto-generated by `npx tsx scripts/gen-intent-catalog.ts`. Do not edit by hand.",
  );
  lines.push("");
  lines.push("| kind | governor | handler | async | p95 latency | error rate | cost p95 |");
  lines.push("|---|---|---|---|---|---|---|");
  for (const k of [...INTENT_KINDS].sort((a, b) => a.kind.localeCompare(b.kind))) {
    const slo = SLO_BY_KIND.get(k.kind);
    lines.push(
      `| \`${k.kind}\` | ${k.governor} | ${k.handler} | ${k.async ? "async" : "sync"} | ${slo ? `${slo.p95LatencyMs} ms` : "—"} | ${slo ? `${(slo.errorRatePct * 100).toFixed(1)}%` : "—"} | ${slo ? `$${slo.costP95Usd}` : "—"} |`,
    );
  }
  lines.push("");
  lines.push("## Descriptions");
  lines.push("");
  for (const k of [...INTENT_KINDS].sort((a, b) => a.kind.localeCompare(b.kind))) {
    lines.push(`- **${k.kind}** — ${k.description}`);
  }
  lines.push("");
  await fs.writeFile(OUT, lines.join("\n"), "utf8");
  console.log(`Wrote ${OUT} with ${INTENT_KINDS.length} intent kinds.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
