/**
 * registry.generated.ts — Public re-export surface over the runtime
 * manifest registry.
 *
 * The actual codegen'd source of truth is
 * `src/server/governance/__generated__/manifest-imports.ts` (regenerated by
 * `npm run manifests:gen`), wired into `registry.ts`. This file exposes a
 * stable, side-effect-free import path for tooling and external consumers
 * who want manifest aggregations without depending on the runtime registry's
 * internal Maps.
 *
 * Type-safe consumption:
 *   import { ALL_MANIFESTS, getManifest } from "@/server/governance/registry.generated";
 */

import type { NeteruManifest } from "./manifest";
import { getAllManifests, getManifest as runtimeGetManifest } from "./registry";

export const ALL_MANIFESTS = (): readonly NeteruManifest[] => getAllManifests();

export function getManifest(serviceSlug: string): NeteruManifest | undefined {
  return runtimeGetManifest(serviceSlug);
}

export function findHandlerForIntent(kind: string): NeteruManifest | undefined {
  return getAllManifests().find((m) => m.acceptsIntents?.includes(kind));
}

export function listEmittedIntents(): readonly string[] {
  const set = new Set<string>();
  for (const m of getAllManifests()) {
    for (const k of m.emits ?? []) set.add(k);
  }
  return Array.from(set).sort();
}

export function listAcceptedIntents(): readonly string[] {
  const set = new Set<string>();
  for (const m of getAllManifests()) {
    for (const k of m.acceptsIntents ?? []) set.add(k);
  }
  return Array.from(set).sort();
}
