/**
 * gen-app-routes.ts — generate a manifest of navigable app-router page routes.
 *
 * Consumed by the breadcrumb so it only linkifies paths that actually resolve
 * (site-prober finding: the breadcrumb linked index-less section roots like
 * `/console/socle` → 404). Re-run after adding/removing routes:
 *
 *   npm run gen:routes
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";
import { discoverStaticRoutes } from "./site-prober/routes";

const routes = discoverStaticRoutes("src/app");
const target = "src/lib/generated/app-routes.ts";

const body = `// AUTO-GENERATED by scripts/gen-app-routes.ts — do not edit by hand.
// Run \`npm run gen:routes\` after adding/removing page routes.
//
// The breadcrumb uses this to linkify only navigable paths (site-prober
// finding: index-less section roots like /console/socle were linked → 404).
export const APP_ROUTES: ReadonlySet<string> = new Set([
${routes.map((r) => `  ${JSON.stringify(r)},`).join("\n")}
]);
`;

mkdirSync(dirname(target), { recursive: true });
writeFileSync(target, body);
console.log(`gen-app-routes: wrote ${routes.length} routes to ${target}`);
