/**
 * scripts/inventory-glory-tools.ts — Snapshot the GLORY tools registry.
 *
 * Run: `npm run glory:inventory`.
 * Output: docs/governance/glory-tools-inventory.md
 *
 * Reads the actual runtime registry, including every imported tool family.
 * Each row comes from one tool; unrelated regex matches cannot shift fields.
 */

import { promises as fs } from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import { EXTENDED_GLORY_TOOLS } from "../src/server/services/artemis/tools/registry";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUT = path.join(ROOT, "docs", "governance", "glory-tools-inventory.md");

async function main() {
  const rows = EXTENDED_GLORY_TOOLS.map((tool) => ({
    slug: tool.slug,
    layer: tool.layer,
    execType: tool.executionType,
    status: tool.status,
  }));
  if (new Set(rows.map((r) => r.slug)).size !== rows.length) {
    throw new Error("Duplicate tool identities in the runtime registry.");
  }

  const layerCount: Record<string, number> = {};
  const execCount: Record<string, number> = {};
  for (const r of rows) {
    layerCount[r.layer] = (layerCount[r.layer] ?? 0) + 1;
    execCount[r.execType] = (execCount[r.execType] ?? 0) + 1;
  }

  const lines: string[] = [];
  lines.push("# GLORY Tools Inventory");
  lines.push("");
  lines.push(
    `Auto-generated by \`npm run glory:inventory\`. ${rows.length} tools indexed.`,
  );
  lines.push("");
  lines.push("## Counts by layer");
  lines.push("");
  for (const [k, v] of Object.entries(layerCount).sort()) {
    lines.push(`- **${k}**: ${v}`);
  }
  lines.push("");
  lines.push("## Counts by execution type");
  lines.push("");
  for (const [k, v] of Object.entries(execCount).sort()) {
    lines.push(`- **${k}**: ${v}`);
  }
  lines.push("");
  lines.push("## Tools");
  lines.push("");
  lines.push("| slug | layer | execType | status |");
  lines.push("|---|---|---|---|");
  for (const r of rows) {
    lines.push(
      `| \`${r.slug}\` | ${r.layer} | ${r.execType} | ${r.status} |`,
    );
  }
  lines.push("");

  await fs.writeFile(OUT, lines.join("\n"), "utf8");
  console.log(`Wrote ${OUT} with ${rows.length} tools.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
