/**
 * scripts/inventory-glory-tools.ts — Snapshot the GLORY tools registry.
 *
 * Run: `npm run glory:inventory`.
 * Output: docs/governance/glory-tools-inventory.md
 *
 * Parses src/server/services/artemis/tools/registry.ts (text scan — the file
 * is a single typed const) and emits a Markdown table with one row per tool:
 *   slug | layer | execType | status | inputs (count) | outputs (count) | notes
 */

import { promises as fs } from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const TOOLS_DIR = path.join(ROOT, "src", "server", "services", "artemis", "tools");
// Phase 13 (B2) — scanner registry.ts + tous les fichiers phase*-oracle-tools.ts
const SOURCE_FILES = ["registry.ts", "phase13-oracle-tools.ts"];
const OUT = path.join(ROOT, "docs", "governance", "glory-tools-inventory.md");

async function main() {
  const allSrc: string[] = [];
  for (const fname of SOURCE_FILES) {
    const fpath = path.join(TOOLS_DIR, fname);
    try {
      const content = await fs.readFile(fpath, "utf8");
      allSrc.push(content);
    } catch (e) {
      // file may not exist (legacy or future addition) — skip silently
      void e;
    }
  }
  const src = allSrc.join("\n");
  const slugs = [...src.matchAll(/slug:\s*"([a-z0-9-]+)"/g)].map((m) => m[1]!);
  const layers = [...src.matchAll(/layer:\s*"([A-Z]+)"/g)].map((m) => m[1]!);
  const execTypes = [...src.matchAll(/executionType:\s*"([A-Z]+)"/g)].map(
    (m) => m[1]!,
  );
  const statuses = [...src.matchAll(/status:\s*"([A-Z]+)"/g)].map((m) => m[1]!);

  const rows = slugs.map((slug, i) => ({
    slug,
    layer: layers[i] ?? "?",
    execType: execTypes[i] ?? "?",
    status: statuses[i] ?? "?",
  }));

  const layerCount: Record<string, number> = {};
  const execCount: Record<string, number> = {};
  for (const r of rows) {
    layerCount[r.layer] = (layerCount[r.layer] ?? 0) + 1;
    execCount[r.execType] = (execCount[r.execType] ?? 0) + 1;
  }

  const lines: string[] = [];
  lines.push("# GLORY Tools Inventory");
  lines.push("");
  lines.push(
    `Auto-generated by \`npm run glory:inventory\`. ${rows.length} tools indexed.`,
  );
  lines.push("");
  lines.push("## Counts by layer");
  lines.push("");
  for (const [k, v] of Object.entries(layerCount).sort()) {
    lines.push(`- **${k}**: ${v}`);
  }
  lines.push("");
  lines.push("## Counts by execution type");
  lines.push("");
  for (const [k, v] of Object.entries(execCount).sort()) {
    lines.push(`- **${k}**: ${v}`);
  }
  lines.push("");
  lines.push("## Tools");
  lines.push("");
  lines.push("| slug | layer | execType | status |");
  lines.push("|---|---|---|---|");
  for (const r of rows) {
    lines.push(
      `| \`${r.slug}\` | ${r.layer} | ${r.execType} | ${r.status} |`,
    );
  }
  lines.push("");

  await fs.writeFile(OUT, lines.join("\n"), "utf8");
  console.log(`Wrote ${OUT} with ${rows.length} tools.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
