/**
 * scripts/scaffold-plugin.ts — Plugin scaffold CLI (Tier 3.10 of residual debt).
 *
 * Usage:
 *   npx tsx scripts/scaffold-plugin.ts <plugin-name> [--external] [--intent <KIND>]
 *
 * Generates a minimal La Fusée plugin under `plugins/<plugin-name>/` with:
 *   - manifest.ts  — typed PluginManifest with an Intent kind, capability, sandbox limits
 *   - index.ts     — handler stub returning a deterministic fixture
 *   - README.md    — quickstart + sandbox notes
 *   - package.json — only when `--external` (so the plugin can be published)
 *
 * Plugins under `plugins/` are auto-loaded by the registry boot sequence;
 * external plugins (`--external`) live as standalone npm packages and
 * register via the `@lafusee/sdk` runtime.
 */

import { mkdirSync, writeFileSync, existsSync } from "node:fs";
import path from "node:path";

interface ParsedArgs {
  name: string;
  external: boolean;
  intent: string;
}

function parseArgs(argv: string[]): ParsedArgs {
  const args = argv.slice(2);
  if (args.length === 0 || args[0]?.startsWith("--")) {
    console.error("Usage: tsx scripts/scaffold-plugin.ts <plugin-name> [--external] [--intent <KIND>]");
    process.exit(1);
  }
  const name = args[0]!;
  if (!/^[a-z][a-z0-9-]+$/.test(name)) {
    console.error("Plugin name must be lowercase kebab-case (e.g., my-plugin).");
    process.exit(1);
  }
  const external = args.includes("--external");
  const intentIdx = args.indexOf("--intent");
  const intent = intentIdx >= 0 && args[intentIdx + 1]
    ? args[intentIdx + 1]!
    : `${name.replace(/-/g, "_").toUpperCase()}_RUN`;
  return { name, external, intent };
}

const { name, external, intent } = parseArgs(process.argv);

const targetDir = external
  ? path.resolve(`packages/plugin-${name}`)
  : path.resolve(`plugins/${name}`);

if (existsSync(targetDir)) {
  console.error(`Target directory already exists: ${targetDir}`);
  process.exit(1);
}

mkdirSync(targetDir, { recursive: true });

const camelName = name
  .split("-")
  .map((s, i) => (i === 0 ? s : s.charAt(0).toUpperCase() + s.slice(1)))
  .join("");

// ── manifest.ts ────────────────────────────────────────────────────────

const manifestContent = `/**
 * @lafusee/${name} — La Fusée plugin.
 *
 * Generated by scripts/scaffold-plugin.ts. Refine schemas, sandbox limits,
 * and capability semantics before publishing.
 */

import { z } from "zod";
${external
  ? `import { defineManifest } from "@lafusee/sdk";\nimport type { PluginManifest } from "@lafusee/sdk";`
  : `import { defineManifest } from "@/server/governance/manifest";\nimport type { PluginManifest } from "@/server/governance/plugin-sandbox";`}

export const manifest: PluginManifest = {
  ...defineManifest({
    service: "${name}",
    governor: "INFRASTRUCTURE",
    version: "0.1.0",
    acceptsIntents: ["${intent}"],
    emits: [],
    capabilities: [
      {
        name: "${camelName}",
        inputSchema: z.object({ strategyId: z.string() }),
        outputSchema: z.object({ ok: z.boolean(), value: z.unknown() }),
        sideEffects: ["DB_READ"],
        idempotent: true,
        missionContribution: "GROUND_INFRASTRUCTURE",
        groundJustification: "Replace with the real reason this plugin advances the mission.",
      },
    ],
    dependencies: [],
    missionContribution: "GROUND_INFRASTRUCTURE",
    groundJustification: "Replace with the real reason this plugin advances the mission.",
  }),
  sandbox: {
    allowedTables: [], // ← whitelist e.g. ["Strategy", "SuperfanProfile"]
    allowedSideEffects: ["DB_READ"],
    maxRowsPerRead: 500,
    maxExecutionMs: 5000,
  },
};
`;

writeFileSync(path.join(targetDir, "manifest.ts"), manifestContent, "utf8");

// ── index.ts ────────────────────────────────────────────────────────

const indexContent = `/**
 * @lafusee/${name} — handler.
 *
 * Receives a sandboxed Prisma client (from plugin-sandbox), so DB access
 * is limited to the tables declared in manifest.sandbox.allowedTables.
 */

import type { z } from "zod";
import type { PluginRuntime } from "${external ? "@lafusee/sdk" : "@/server/governance/plugin-sandbox"}";
import { manifest } from "./manifest";

export type Input = z.infer<(typeof manifest.capabilities)[0]["inputSchema"]>;
export type Output = z.infer<(typeof manifest.capabilities)[0]["outputSchema"]>;

export async function ${camelName}(
  input: Input,
  ctx: PluginRuntime,
): Promise<Output> {
  // TODO — implement. Example: read a strategy and return its name.
  void ctx; // remove once you start using ctx.db
  return { ok: true, value: { strategyId: input.strategyId } };
}

export { manifest };
`;

writeFileSync(path.join(targetDir, "index.ts"), indexContent, "utf8");

// ── README.md ──────────────────────────────────────────────────────

const readmeContent = `# @lafusee/${name}

Generated plugin scaffold.

## Quickstart

1. Refine \`manifest.ts\` — set the right \`Intent\` kind, capability schema, and sandbox limits.
2. Implement the handler in \`index.ts\`.
3. ${external
    ? "Publish: `npm publish --access public` (or use a private registry)."
    : "The plugin auto-loads at boot; no further wiring required."}

## Sandbox

This plugin runs inside the La Fusée plugin sandbox (cf. ADR-0008). Allowed
side-effects and tables are declared in \`manifest.sandbox\`. Any Prisma call
outside the whitelist throws \`SandboxViolation\`.

Default limits (override in \`manifest.sandbox\`):

- \`allowedTables\`: empty (you must whitelist explicitly)
- \`allowedSideEffects\`: \`["DB_READ"]\`
- \`maxRowsPerRead\`: 500
- \`maxExecutionMs\`: 5000

## Intent

This plugin accepts the \`${intent}\` Intent. Trigger via:

\`\`\`ts
await mestor.emitIntent({ kind: "${intent}", strategyId, ... });
\`\`\`
`;

writeFileSync(path.join(targetDir, "README.md"), readmeContent, "utf8");

// ── package.json (external only) ───────────────────────────────────

if (external) {
  const pkg = {
    name: `@lafusee/${name}`,
    version: "0.1.0",
    main: "dist/index.js",
    types: "dist/index.d.ts",
    files: ["dist", "manifest.ts", "index.ts", "README.md"],
    peerDependencies: {
      "@lafusee/sdk": "^0.1.0",
      zod: "^3.0.0",
    },
    scripts: {
      build: "tsc",
    },
    license: "UNLICENSED",
  };
  writeFileSync(path.join(targetDir, "package.json"), JSON.stringify(pkg, null, 2) + "\n", "utf8");
  writeFileSync(
    path.join(targetDir, "tsconfig.json"),
    JSON.stringify(
      {
        compilerOptions: {
          target: "ES2022",
          module: "ESNext",
          moduleResolution: "bundler",
          declaration: true,
          outDir: "dist",
          strict: true,
          esModuleInterop: true,
        },
        include: ["index.ts", "manifest.ts"],
      },
      null,
      2,
    ) + "\n",
    "utf8",
  );
}

console.log(`✓ scaffolded ${external ? "external" : "in-tree"} plugin at ${targetDir}`);
console.log(`  - manifest.ts (Intent: ${intent})`);
console.log(`  - index.ts (handler stub)`);
console.log(`  - README.md`);
if (external) console.log("  - package.json + tsconfig.json (external publish)");
console.log(`\nNext: refine manifest.sandbox limits, implement index.ts, then ${external ? "publish" : "restart your dev server"}.`);
