/**
 * AUTO-GENERATED — do not edit by hand.
 * Generated by `npm run manifests:gen` (scripts/gen-manifest-registry.ts).
 */

import type { NeteruManifest } from "../manifest";

import { manifest as advertisScorerManifest } from "@/server/services/advertis-scorer/manifest";
import { manifest as artemisManifest } from "@/server/services/artemis/manifest";
import { manifest as bootSequenceManifest } from "@/server/services/boot-sequence/manifest";
import { manifest as feedbackLoopManifest } from "@/server/services/feedback-loop/manifest";
import { manifest as financialBrainManifest } from "@/server/services/financial-brain/manifest";
import { manifest as gloryToolsManifest } from "@/server/services/glory-tools/manifest";
import { manifest as ingestionPipelineManifest } from "@/server/services/ingestion-pipeline/manifest";
import { manifest as jehutyManifest } from "@/server/services/jehuty/manifest";
import { manifest as llmGatewayManifest } from "@/server/services/llm-gateway/manifest";
import { manifest as mestorManifest } from "@/server/services/mestor/manifest";
import { manifest as notoriaManifest } from "@/server/services/notoria/manifest";
import { manifest as pillarGatewayManifest } from "@/server/services/pillar-gateway/manifest";
import { manifest as pillarVersioningManifest } from "@/server/services/pillar-versioning/manifest";
import { manifest as quickIntakeManifest } from "@/server/services/quick-intake/manifest";
import { manifest as seshatManifest } from "@/server/services/seshat/manifest";
import { manifest as stalenessPropagatorManifest } from "@/server/services/staleness-propagator/manifest";
import { manifest as strategyPresentationManifest } from "@/server/services/strategy-presentation/manifest";

export const MANIFESTS: readonly NeteruManifest[] = [
  advertisScorerManifest,
  artemisManifest,
  bootSequenceManifest,
  feedbackLoopManifest,
  financialBrainManifest,
  gloryToolsManifest,
  ingestionPipelineManifest,
  jehutyManifest,
  llmGatewayManifest,
  mestorManifest,
  notoriaManifest,
  pillarGatewayManifest,
  pillarVersioningManifest,
  quickIntakeManifest,
  seshatManifest,
  stalenessPropagatorManifest,
  strategyPresentationManifest,
];
