/** Shared presentation labels; extracted from the existing cockpit renderer. */
const LABELS: Record<string, string> = {
  "manipulationMatrix.evaluations.weight": "Part du mix",
  campaignBudgetSummary: "Couverture des budgets de campagne",
  totalsByCurrency: "Montants par devise", unknownBudgetCount: "Budgets à préciser",
  unknownCurrencyCount: "Devises à préciser", budgetCurrency: "Devise du budget",
  nomMarque: "Nom de la marque", accroche: "Accroche", description: "Description",
  secteur: "Secteur", pays: "Pays", brandNature: "Nature", langue: "Langue",
  archetype: "Archetype", archetypeSecondary: "Archetype secondaire",
  citationFondatrice: "Citation fondatrice", noyauIdentitaire: "Noyau identitaire",
  publicCible: "Public cible", promesseFondamentale: "Croyance fondamentale",
  positionnement: "Positionnement", promesseMaitre: "Promesse maitre",
  personas: "Personas", paysageConcurrentiel: "Concurrents",
  tonDeVoix: "Ton de voix", assetsLinguistiques: "Assets linguistiques",
  directionArtistique: "Direction artistique", sousPromesses: "Sous-promesses",
  archetypalExpression: "Expression de l'archetype",
  produitsCatalogue: "Catalogue produits", productLadder: "Echelle produit",
  unitEconomics: "Unit Economics", businessModel: "Modele d'affaires",
  positioningArchetype: "Positionnement prix", salesChannel: "Canal de vente",
  pricingJustification: "Justification du pricing",
  personaSegmentMap: "Mapping persona-produit",
  touchpoints: "Touchpoints", rituels: "Rituels", aarrr: "Funnel AARRR",
  kpis: "KPIs", superfanPortrait: "Portrait du superfan",
  promesseExperience: "Promesse d'experience",
  conversionTriggers: "Triggers de conversion", barriersEngagement: "Barrieres",
  globalSwot: "SWOT", probabilityImpactMatrix: "Matrice de risques",
  mitigationPriorities: "Priorites de mitigation", riskScore: "Score de risque",
  overtonBlockers: "Blocages Overton", pillarGaps: "Diagnostic par pilier",
  coherenceRisks: "Risques de coherence", devotionVulnerabilities: "Vulnerabilites Engagement",
  triangulation: "Triangulation marche", hypothesisValidation: "Hypotheses",
  tamSamSom: "TAM / SAM / SOM", brandMarketFitScore: "Brand-Market Fit",
  overtonPosition: "Position Overton", perceptionGap: "Ecart de perception",
  riskValidation: "Validation des risques", competitorOvertonPositions: "Concurrents Overton",
  catalogueParCanal: "Catalogue par canal", assetsProduisibles: "Assets produisibles",
  activationsPossibles: "Activations", innovationsProduit: "Innovations produit",
  actionsByDevotionLevel: "Actions par Engagement", riskMitigationActions: "Actions de mitigation",
  hypothesisTestActions: "Tests d'hypotheses", formatsDisponibles: "Formats disponibles",
  fenetreOverton: "Fenetre d'Overton", roadmap: "Roadmap",
  sprint90Days: "Sprint 90 jours", selectedFromI: "Actions selectionnees depuis I",
  devotionFunnel: "Funnel Engagement", overtonMilestones: "Jalons Overton",
  northStarKPI: "North Star KPI", budgetByDevotion: "Budget par Engagement",
  axesStrategiques: "Axes strategiques", facteursClesSucces: "Facteurs cles de succes",
  valeurs: "Valeurs", herosJourney: "Parcours du heros", ikigai: "Ikigai",
  enemy: "Ennemi", prophecy: "Prophetie", doctrine: "Doctrine",
  livingMythology: "Mythologie vivante", hierarchieCommunautaire: "Hierarchie communautaire",
  equipeDirigeante: "Equipe dirigeante", equipeComplementarite: "Complementarite equipe",
  timelineNarrative: "Timeline narrative", totalActions: "Total actions",
  globalBudget: "Budget global", coherenceScore: "Coherence",
  syntheseExecutive: "Synthese executive", visionStrategique: "Vision strategique",
  promesseDeValeur: "Promesse de valeur", mvp: "MVP", proprieteIntellectuelle: "Propriete intellectuelle",
  gamification: "Gamification", principesCommunautaires: "Principes communautaires",
  sacredCalendar: "Calendrier sacre", commandments: "Commandements",
  ritesDePassage: "Rites de passage", sacraments: "Sacrements", taboos: "Tabous",
  sacredObjects: "Objets sacres", proofPoints: "Proof Points", symboles: "Symboles",
  rejectedFromI: "Actions rejetees", recommandationsPrioritaires: "Recommandations",
  marketReality: "Realite marche", weakSignalAnalysis: "Signaux faibles",
  traction: "Traction", marketDataSources: "Sources de donnees",
  brandPlatform: "Plateforme de marque", copyStrategy: "Copy strategy",
  bigIdea: "Big Idea", potentielBudget: "Budget potentiel", mediaPlan: "Plan media",
  productExperienceMap: "Experience par produit", ladderProductAlignment: "Engagement x Produit",
  channelTouchpointMap: "Canaux x Touchpoints",
  economicModels: "Modeles economiques", freeLayer: "Layer gratuit",
  kpiDashboard: "KPI Dashboard", teamStructure: "Equipe mobilisee",
  budgetBreakdown: "Ventilation budget",
  // ── ADR-0037 PR-K — nouveaux fields canon manuel ADVE ──
  messieFondateur: "Figure fondatrice", competencesDivines: "Compétences clés",
  preuvesAuthenticite: "Preuves d'authenticite", indexReputation: "Index de reputation",
  eNps: "eNPS", turnoverRate: "Turnover interne",
  missionStatement: "Mission Statement", originMyth: "Origin Myth",
  positionnementEmotionnel: "Positionnement emotionnel", swotFlash: "SWOT Flash",
  esov: "ESOV", barriersImitation: "Barrieres imitation",
  storyEvidenceRatio: "Storytelling / Evidence",
  roiProofs: "ROI Proofs", experienceMultisensorielle: "Architecture Multisensorielle",
  sacrificeRequis: "Sacrifice Requis", packagingExperience: "Packaging & Delivery",
  clergeStructure: "Le Clerge", pelerinages: "Les Pelerinages",
  programmeEvangelisation: "Programme d'Evangelisation",
  communityBuilding: "Community Building",
  // Atom-level labels
  action: "Action", nom: "Nom", name: "Nom", format: "Format", objectif: "Objectif",
  pilierImpact: "Pilier impacte", devotionImpact: "Impact Engagement", overtonShift: "Shift Overton",
  canal: "Canal", cible: "Cible", budgetEstime: "Budget estime", activation: "Activation",
  type: "Type", feasibility: "Faisabilite", horizon: "Horizon", phase: "Phase",
  duree: "Duree", budget: "Budget", objectifDevotion: "Objectif Engagement",
  priority: "Priorite", owner: "Responsable", kpi: "KPI", isRiskMitigation: "Mitigation risque",
  sourceRef: "Source", age: "Age", csp: "CSP", location: "Localisation",
  income: "Revenu", familySituation: "Situation familiale", motivations: "Motivations",
  fears: "Craintes", hiddenDesire: "Desir cache", lifestyle: "Style de vie",
  devotionPotential: "Potentiel Engagement", rank: "Rang", prix: "Prix", cout: "Cout",
  margeUnitaire: "Marge unitaire", categorie: "Categorie", segmentCible: "Segment cible",
  phaseLifecycle: "Phase cycle de vie", lienPromesse: "Lien promesse",
  risk: "Risque", probability: "Probabilite", impact: "Impact", mitigation: "Mitigation",
  actNumber: "Acte", title: "Titre", narrative: "Recit", emotionalArc: "Arc emotionnel",
  causalLink: "Lien causal", value: "Valeur", customName: "Nom personnalise",
  justification: "Justification", costOfHolding: "Cout de maintien",
  personnalite: "Personnalite", onDit: "On dit", onNeditPas: "On ne dit pas",
  bio: "Biographie", role: "Role", competencesCles: "Competences cles",
  experiencePasse: "Experience passee", credentials: "Credentials",
  allocationPct: "Allocation temps", manifesto: "Manifesto",
  counterStrategy: "Contre-strategie", marketingCounter: "Contre marketing",
  activeOpposition: "Opposition active", passiveOpposition: "Opposition passive",
  worldTransformed: "Monde transforme", pioneers: "Pionniers", urgency: "Urgence",
  dogmas: "Dogmes", principles: "Principes", practices: "Pratiques",
  gainClientConcret: "Gain client concret",
  gainClientAbstrait: "Gain client abstrait",
  // Hierarchie & communaute
  level: "Niveau", privileges: "Privileges", entryCriteria: "Critere d'entree",
  principle: "Principe", commandment: "Commandement",
  nomSacre: "Nom sacre", reward: "Recompense", kpiMeasure: "KPI de mesure",
  frequency: "Frequence", date: "Date", significance: "Signification",
  rituelEntree: "Rituel d'entree", fromStage: "De", toStage: "Vers",
  taboo: "Tabou", consequence: "Consequence",
  // Timeline narrative sub-fields
  origine: "Origine",
  transformation: "Transformation", present: "Present", futur: "Futur",
  // Mythologie & cult marketing
  foundingMyth: "Mythe fondateur", heroicMoments: "Moments heroiques",
  sacredRituals: "Rituels sacres", canon: "Canon", extensionRules: "Regles d'extension",
  captureSystem: "Systeme de capture", sharedHatred: "Haine partagee",
  bondingRituals: "Rituels de cohesion", fraternityFuel: "Carburant de fraternite",
  overtonMap: "Carte Overton", ourPosition: "Notre position",
  enemyPosition: "Position ennemie", battleground: "Terrain de combat",
  shiftDirection: "Direction du shift", enemyBrands: "Marques ennemies",
  howTheyFight: "Leur strategie", enemySchwartzValues: "Valeurs ennemies",
  // Direction artistique
  semioticAnalysis: "Analyse semiotique", visualLandscape: "Paysage visuel",
  moodboard: "Moodboard", chromaticStrategy: "Stratégie chromatique",
  typographySystem: "Systeme typographique", logoTypeRecommendation: "Recommandation logo",
  logoValidation: "Validation logo", designTokens: "Design tokens",
  motionIdentity: "Identite mouvement", brandGuidelines: "Charte graphique",
  lsiMatrix: "Matrice LSI", dominantSigns: "Signes dominants",
  gloryOutputId: "ID Glory",
  // Engagement
  personaRef: "Persona ref", productRef: "Produit ref",
  touchpointRefs: "Touchpoints", emotionalOutcome: "Resultat emotionnel",
  experienceDescription: "Experience", entryAction: "Action d'entree",
  upgradeAction: "Action d'upgrade", fromLevel: "De", toLevel: "Vers",
  trigger: "Declencheur", barrier: "Barriere", enforcement: "Application",
  // Assets & Identite
  slogan: "Slogan", tagline: "Tagline", motto: "Devise",
  mantras: "Mantras", lexiquePropre: "Lexique propre",
  languePrincipale: "Langue principale", languesSecondaires: "Langues secondaires",
  word: "Mot", definition: "Definition",
  sign: "Signe", meaning: "Signification", culturalContext: "Contexte culturel",
  archetypeVisual: "Archetype visuel", semioticTensions: "Tensions semiotiques",
  tension: "Tension", resolution: "Resolution",
  competitors: "Concurrents", visualIdentity: "Identite visuelle",
  differentiator: "Differenciateur", whitespace: "Espace blanc",
  positioningMap: "Carte de positionnement", xAxis: "Axe X", yAxis: "Axe Y",
  brandPosition: "Position de marque",
  theme: "Theme", keywords: "Mots-cles",
  colorPalette: "Palette de couleurs", hex: "Hex", usage: "Usage",
  textures: "Textures", references: "References", source: "Source",
  primaryColors: "Couleurs primaires", secondaryColors: "Couleurs secondaires",
  emotion: "Emotion", gradients: "Degrades", from: "De", to: "Vers",
  forbiddenColors: "Couleurs interdites", reason: "Raison",
  accessibilityNotes: "Notes accessibilite",
  primaryFont: "Police principale", secondaryFont: "Police secondaire",
  category: "Categorie", size: "Taille", weight: "Graisse",
  hierarchy: "Hierarchie", rules: "Regles",
  logoType: "Type de logo", rationale: "Justification",
  variations: "Variations", doNots: "A eviter",
  strengths: "Forces", weaknesses: "Faiblesses",
  recommendations: "Recommandations", culturalFit: "Adequation culturelle",
  spacing: "Espacements", borderRadius: "Rayons de bordure",
  shadows: "Ombres", breakpoints: "Points de rupture",
  personality: "Personnalite", transitions: "Transitions",
  duration: "Duree", easing: "Courbe", microInteractions: "Micro-interactions",
  animation: "Animation",
  sections: "Sections", content: "Contenu",
  dosAndDonts: "A faire / A eviter",
  applicationExamples: "Exemples d'application", medium: "Support",
  concepts: "Concepts", layers: "Couches",
  sublimationRules: "Regles de sublimation", literal: "Litteral", sublimated: "Sublime",
  // Engagement sacre
  socialSignal: "Signal social", form: "Forme", stage: "Stade",
  claim: "Affirmation",
  symbol: "Symbole", meanings: "Significations", usageContexts: "Contextes d'usage",
  // Concurrents
  partDeMarcheEstimee: "Part de marche estimee", avantagesCompetitifs: "Avantages competitifs",
  faiblesses: "Faiblesses", strategiePos: "Stratégie de positionnement",
  distinctiveAssets: "Assets distinctifs", menaceNiveau: "Menace",
  // Generics
  score: "Score", gaps: "Lacunes", pillar1: "Pilier 1", pillar2: "Pilier 2",
  field1: "Champ 1", field2: "Champ 2", contradiction: "Contradiction",
  severity: "Severite", status: "Statut", evidence: "Preuve",
  hypothesis: "Hypothese", validationMethod: "Methode de validation",
  // V — Pricing & Economics
  whatIsFree: "Ce qui est gratuit",
  whatIsPaid: "Ce qui est payant", conversionLever: "Levier de conversion",
  cac: "Cout d'acquisition",
  ltv: "Valeur vie client", ltvCacRatio: "Ratio LTV/CAC",
  pointMort: "Point mort", margeNette: "Marge nette",
  roiEstime: "ROI estime", paybackPeriod: "Periode de retour",
  budgetCom: "Budget communication", caVise: "CA vise",
  riskHedging: "Couverture de risque",
  canalDistribution: "Canal distribution", disponibilite: "Disponibilite",
  skuRef: "Reference SKU", produitIds: "Produits",
  exists: "Existe", features: "Fonctionnalites",
  launchDate: "Date de lancement", userCount: "Utilisateurs",
  feedbackSummary: "Resume feedback",
  brevets: "Brevets", statut: "Statut", numero: "Numero",
  secretsCommerciaux: "Secrets commerciaux",
  technologieProprietary: "Technologie proprietaire",
  barrieresEntree: "Barrieres a l'entree", licences: "Licences",
  protectionScore: "Score de protection",
  gainMarqueConcret: "Gain marque concret", gainMarqueAbstrait: "Gain marque abstrait",
  coutClientConcret: "Cout client concret", coutClientAbstrait: "Cout client abstrait",
  coutMarqueConcret: "Cout marque concret", coutMarqueAbstrait: "Cout marque abstrait",
  valeurMarqueTangible: "Valeur marque tangible", valeurMarqueIntangible: "Valeur marque intangible",
  valeurClientTangible: "Valeur client tangible", valeurClientIntangible: "Valeur client intangible",
  coutMarqueTangible: "Cout marque tangible", coutMarqueIntangible: "Cout marque intangible",
  coutClientTangible: "Cout client tangible", coutClientIntangible: "Cout client intangible",
  // E — Engagement
  primaryChannel: "Canal principal",
  aarrStage: "Etape AARRR", aarrPrimary: "AARRR principal",
  // R — Risk
  blockingPerception: "Perception bloquante", devotionLevelBlocked: "Niveau Engagement bloque",
  churnCause: "Cause de desabonnement",
  // T — Track
  macroTrends: "Tendances macro", weakSignals: "Signaux faibles",
  currentPerception: "Perception actuelle", targetPerception: "Perception cible",
  measurementMethod: "Methode de mesure", measuredAt: "Mesure le",
  confidence: "Confiance", segment: "Segment", perception: "Perception",
  gapDescription: "Description de l'ecart", gapScore: "Score ecart",
  relativeToUs: "Position relative",
  customerInterviews: "Entretiens clients", competitiveAnalysis: "Analyse concurrentielle",
  trendAnalysis: "Analyse tendances", financialBenchmarks: "Benchmarks financiers",
  // S — Strategie
  axe: "Axe", pillarsLinked: "Piliers lies",
  perceptionActuelle: "Perception actuelle", perceptionCible: "Perception cible",
  ecart: "Ecart", strategieDeplacement: "Stratégie de déplacement",
  etape: "Etape", devotionTarget: "Cible Engagement", riskRef: "Ref risque",
  hypothesisRef: "Ref hypothese", responsibility: "Responsabilite",
  pillar: "Pilier", target: "Objectif",
  spectateurs: "Spectateurs", interesses: "Interesses",
  participants: "Participants", engages: "Engages",
  ambassadeurs: "Ambassadeurs", evangelistes: "Prescripteurs",
  acquisition: "Acquisition", conversion: "Conversion",
  retention: "Retention", evangelisation: "Recommandation",
  currentValue: "Valeur actuelle", recommendation: "Recommandation",
  // Labels shared by the plan, Oracle HTML and exports.
  budgetSummary: "Chiffrage des initiatives",
  partDeMarche: "Part de marché",
  knownSubtotal: "Sous-total chiffré",
  declaredSubtotal: "Montants déclarés",
  estimatedSubtotal: "Montants estimés",
  declaredCount: "Budgets déclarés",
  estimatedCount: "Estimations",
  unknownCount: "Budgets à préciser",
  unassignedTimeframeCount: "Échéances à préciser",
  projectionAssumptions: "Hypothèses de projection",
  recommended: "Recommandé",
  selected: "Retenu",
  baseGrowthPct: "Croissance de référence (%)",
  baseCultIndex: "Indice d’attachement de référence",
  riskCoveragePct: "Couverture des risques (%)",
  riskCoverageSource: "Origine de la couverture des risques",
  cultIndexSource: "Origine de l’indice d’attachement",
  growthSource: "Origine de la croissance",
  baseCultIndexSource: "Origine de l’indice de référence",
  key: "Référence",
  label: "Libellé",
  items: "Éléments",
  state: "État",
  summary: "Synthèse",
  budgetBasis: "Origine du chiffrage",
  channel: "Canal",
  timeframe: "Échéance",
  totalCount: "Éléments recensés",
  classifiedCount: "Éléments classés",
  unassignedCount: "Éléments à planifier",
  coverage: "État de la classification",
  unassigned: "Échéances à préciser",
  mckinsey7s: "Cohérence organisationnelle — 7S",
  mckinsey3Horizons: "Trois horizons de croissance",
  bcgPortfolio: "Portefeuille d’offres",
  bcgStrategyPalette: "Palette stratégique",
  deloitteBudget: "Plan budgétaire",
  deloitteGreenhouse: "Capacité de l’équipe",
  bainNps: "Recommandation client",
  cultIndex: "Indice d’attachement",
  devotionLadder: "Échelle d’engagement",
  overtonDistinctive: "Position culturelle",
  tarsisWeakSignals: "Signaux sectoriels",
  manipulationMatrix: "Modes d’engagement",
  crewProgram: "Programme d’équipe",
  commsPlan: "Plan de diffusion",
  strategy: "Stratégie",
  structure: "Organisation",
  systems: "Systèmes",
  shared_values: "Valeurs partagées",
  style: "Style",
  staff: "Équipe",
  skills: "Compétences",
  gap: "Écart",
  team_profiles: "Profils de l’équipe",
  complementarity_score: "Complémentarité",
  execution_capacity: "Capacité d’exécution",
  skill_gaps: "Compétences à compléter",
  total_budget: "Budgets des campagnes",
  allocation_par_categorie: "Ventilation par poste",
  repartition_initiatives_par_intensite: "Initiatives par intensité budgétaire",
  alternatives_economiques: "Options économiques",
  methodologie: "Méthode de calcul",
  allocation: "Répartition (%)",
  observed: "Constat",
  dominantMode: "Mode principal",
  mixSource: "Origine de la répartition",
  rituelsDeclares: "Rituels déclarés",
  touchpointsDeclares: "Points de contact déclarés",
  profile: "Profil",
  barriers: "Freins",
  current_position: "Position actuelle",
  target_position: "Position cible",
  maneuvers: "Actions de déplacement",
  realSignal: "Mesure de la position",
  degradationCodes: "Données manquantes",
  observedAt: "Date du constat",
  LOW: "Économique",
  MEDIUM: "Modéré",
  HIGH: "Intensif",
  initiativeCount: "Nombre d’initiatives",
  initiativeIds: "Références des actions",
  projectedGrowthPct: "Croissance projetée (%)",
  projectedRevenue: "Revenus projetés",
  targetCultIndex: "Indice d’attachement cible",
  riskCoverage: "Couverture des risques",
  budgetByPhase: "Chiffrage par phase",
  totalBudget: "Budget total",
  estimatedBudgetUsd: "Budget estimé (USD)",

};

function fallbackLabel(key: string): string {
  return key.replace(/([a-z0-9])([A-Z])/g, "$1 $2").replace(/[_-]+/g, " ")
    .trim().replace(/^./, (s) => s.toUpperCase());
}

export function getFieldLabel(key: string, context?: string): string {
  const contextLabel = context ? LABELS[`${context}.${key}`] : undefined;
  if (contextLabel) return contextLabel;
  // ADR-0030 PR-Fix-3 — gérer les paths nested (ex: "unitEconomics.cac"
  // → "Unit Economics → CAC"). Avant : "Unit Economics. Cac" (moche).
  // Chaque segment est mappé via LABELS puis joint avec " → ".
  if (key.includes(".")) {
    return key
      .split(".")
      .map((k) => LABELS[k] ?? fallbackLabel(k))
      .join(" → ");
  }
  return LABELS[key] ?? fallbackLabel(key);
}
